<?php
$title = $this->translate('Adicionar Profissão');
$this->headTitle($title);
$form = $this->form;
$form->prepare();
?>
<h1 class="container-header"><i class="fa fa-suitcase"></i> <?php echo $this->escapeHtml($title); ?></h1>
<?php echo $this->form()->openTag($form); ?>
<div class="form-group">
    <?php $occupation = $form->get('occupation'); ?>
    <?php echo $this->formHidden($occupation->get('occupationId')); ?>
    <div class="row">
        <div class="col-md-4">
            <?php echo $this->formLabel($occupation->get('occupationName')); ?>
            <?php echo $this->formText($occupation->get('occupationName')); ?>
        </div>
    </div>
</div>
<?php echo $this->formHidden($form->get('security')); ?>
<div class="btn-group">
    <?php echo $this->formElement($form->get('submit')); ?>
    <?php echo $this->formElement($form->get('cancel')); ?>
</div>
<?php echo $this->form()->closeTag(); ?>
