<?php
$title = $this->translate('Profissão');
$this->headTitle($title);
?>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-6">
                <h4 class="panel-title"><i class="fa fa-suitcase"></i> <?php echo $this->escapeHtml($title); ?></h4>
            </div>
            <div class="col-md-6">
                <div class="btn-group btn-group-sm pull-right">
                    <a class="btn btn-default" href="<?php echo $this->url('admin/occupation/add', array('action' => 'add')); ?>"> <i class="glyphicon glyphicon-plus"></i> <?php echo $this->translate('Novo'); ?></a>
                </div>
            </div>
        </div>
    </div>
    <table class="table table-condensed table-hover">
        <tr>
            <th><?php echo $this->translate('PROFISSÃO'); ?></th>
        </tr>
        <?php if (0 == count($this->occupation)): ?>
            <tr>
                <td colspan="10" class="alert alert-info text-center"><?php echo $this->translate('Não há registros no banco de dados.') ?></td>
            </tr>
        <?php else: ?>
            <?php foreach ($this->occupation as $occupation) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($occupation->getOccupationName()); ?></td>
                    <td>
                        <div class="btn-group btn-group-xs pull-right">
                            <a class="btn btn-default" href="<?php echo $this->url('admin/occupation/edit', array('action' => 'edit', 'id' => $occupation->getOccupationId()))
                    ?>"><i class="glyphicon glyphicon-edit"></i></a>
                            <a class="btn btn-default" href="<?php echo $this->url('admin/occupation/delete', array('action' => 'delete', 'id' => $occupation->getOccupationId()))
                    ?>"><i class="glyphicon glyphicon-remove"></i></a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </table>
    <div class="panel-footer">
        <?php
        $paginationInfo = $this->placeholder('pagination');
        if (!isset($paginationInfo->route)) {
            $paginationInfo->route = 'admin/occupation';
            $paginationInfo->params = array();
        }
        ?>
        <?php echo $this->paginationControl($this->occupation, 'Sliding', 'layout/pagination'); ?>
    </div>
</div>
