<?php
$title = $this->translate('Apagar Fornecedor');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><?php echo $this->translate('Você tem certeza de que deseja apagar ')?>
    '<?php echo $this->escapeHtml($this->supplier->getPerson()->getPersonName()); ?>'?
</p>
<?php
$url = $this->url('admin/supplier/delete', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <input type="hidden" name="id" value="<?php echo $this->supplier->getSupplierId(); ?>" />
<div class="form-actions">
    <input type="submit" name="del" value="Sim" class="btn btn-default" />
    <input type="submit" name="del" value="Não" class="btn btn-default" />
</div>
</form>
