<?php
$title = $this->translate('Caixa');
$this->headTitle($title);
?>
<h1 class="row">
    <div class="col-md-6">
        <h1 class="container-header"><i class="glyphicon glyphicon-shopping-cart"></i> <?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="col-md-6">
    </div> 
</h1>
<div class="row">
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title"><i class="glyphicon glyphicon-usd"></i> Resumo do Caixa</h4>
            </div>
            <div class="panel-body">
                <?php if ((double) $this->lastBalance >= 0): ?>
                    <h4 class="text-info" dir="rtl">
                        <small>Saldo Anterior</small>
                        <?php echo $this->currency((double) $this->lastBalance); ?>
                    </h4>
                <?php else: ?>
                    <h4 class="text-error" dir="rtl">
                        <small>Saldo Anterior</small>
                        <?php echo $this->currency((double) $this->lastBalance); ?>
                    </h4>
                <?php endif; ?>
                <hr/>
                <?php if ((double) $this->balance >= 0): ?>
                    <h4 class="text-info" dir="rtl">
                        <small>Saldo Atual</small>
                        <?php echo $this->currency((double) $this->balance); ?>
                    </h4>
                <?php else: ?>
                    <h4 class="text-error" dir="rtl">
                        <small>Saldo Atual</small>
                        <?php echo $this->currency((double) $this->balance); ?>
                    </h4>
                <?php endif; ?>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title"><i class="glyphicon glyphicon-usd"></i> Resumo do Mês <b><?php echo date('m/Y'); ?></b></h4>
            </div>
            <div class="panel-body">
                <h4 class="text-info" dir="rtl">
                    <small>Entradas</small>
                    <?php echo $this->currency((double) $this->monthRevenues); ?>
                </h4>
                <hr/>
                <h4 class="text-danger" dir="rtl">
                    <small>Saídas</small>
                    <?php echo $this->currency((double) $this->monthExpenses); ?>
                </h4>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title"><i class="fa fa-gear"></i> Opções de Visualização</h4>
            </div>
            <div class="panel-body">
                <form>
                    <div class="input-group">
                        <input type="text" id="dt" name="dt" value="<?php echo date('d/m/Y'); ?>" class="form-control datepicker" />
                        <span class="input-group-btn">
                            <input type="submit" id="submit" name="submit" value="Ok" class="btn btn-default" />
                        </span>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <?php $this->cash; ?>

    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title"><i class="glyphicon glyphicon-usd"></i> Caixa do Dia - <?php echo date('d/m/Y'); ?>
                    <a class="btn btn-default btn-sm pull-right app-tooltip" href="<?php echo $this->url('admin/financial/expense/add', array('action' => 'add')); ?>" title="Nova Despesa"> <i class="fa fa-upload"></i></a>
                    <a class="btn btn-default btn-sm pull-right app-tooltip" href="<?php echo $this->url('admin/financial/revenue/add', array('action' => 'add')); ?>" title="Nova Receita"> <i class="fa fa-download"></i></a>
                    <div>&nbsp;</div>
                </h4>
            </div>
            <table class="table table-condensed table-hover">
                <tr>
                    <th class="col-md-2"><?php echo $this->translate('DATA'); ?></th>
                    <th class=""><?php echo $this->translate('DESCRIÇÃO'); ?></th>
                    <th class=""><?php echo $this->translate('DÉBITO'); ?></th>
                    <th class=""><?php echo $this->translate('CRÉDITO'); ?></th>
                    <th class=""><?php echo $this->translate('SALDO'); ?></th>
                </tr>
                <tr>
                    <td colspan="4" dir="rtl">SALDO ANTERIOR</td>
                    <td><b><?php echo $this->currency($this->lastBalance); ?></b></td>
                </tr>
                <?php if (0 == count($this->cash)): ?>
                    <tr>
                        <td colspan="10" class="text-center"><?php echo $this->info($this->translate('Não há lançamentos no dia até o momento.')) ?></td>
                    </tr>
                <?php else: ?>
                    <?php foreach ($this->cash as $launch) : ?>
                        <?php $cashLaunch = $this->launch($launch->getLaunchId()); ?>
                        <?php if ($cashLaunch instanceof \Financial\Entity\Revenue): ?>
                            <tr class="text-info">
                                <td><?php echo $this->date($launch->getLaunchDate()); ?></td>
                                <td><?php echo $this->escapeHtml($launch->getLaunchDescription()); ?></td>
                                <td>-</td>
                                <td><?php echo $this->currency($launch->getLaunchValue()); ?></td>
                                <td>&nbsp;</td>
                            </tr>
                        <?php elseif ($cashLaunch instanceof \Financial\Entity\Expense): ?>
                            <tr class="text-danger">
                                <td><?php echo $this->date($launch->getLaunchDate()); ?></td>
                                <td><?php echo $this->escapeHtml($launch->getLaunchDescription()); ?></td>
                                <td><?php echo $this->currency($launch->getLaunchValue()); ?></td>
                                <td>-</td>
                                <td>&nbsp;</td>
                            </tr>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
                <tr style="font-weight: bold; background: #fafafa;">
                    <td colspan="2" dir="rtl"><b>TOTAL</b></td>
                    <td class="text-danger"><?php echo $this->currency($this->expense); ?></td>
                    <td class="text-info"><?php echo $this->currency($this->revenue); ?></td>
                    <td><?php echo $this->currency($this->balance); ?></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>