<?php

namespace DoctrineORMModule\Proxy\__CG__\Bank\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Bank extends \Bank\Entity\Bank implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'bankId', 'bankCode', 'bankName', 'bankWebsite', 'bankTax', 'bankReturn', 'bankDirect');
        }

        return array('__isInitialized__', 'bankId', 'bankCode', 'bankName', 'bankWebsite', 'bankTax', 'bankReturn', 'bankDirect');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Bank $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getBankId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getBankId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBankId', array());

        return parent::getBankId();
    }

    /**
     * {@inheritDoc}
     */
    public function setBankId($bankId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBankId', array($bankId));

        return parent::setBankId($bankId);
    }

    /**
     * {@inheritDoc}
     */
    public function getBankCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBankCode', array());

        return parent::getBankCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setBankCode($bankCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBankCode', array($bankCode));

        return parent::setBankCode($bankCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getBankName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBankName', array());

        return parent::getBankName();
    }

    /**
     * {@inheritDoc}
     */
    public function setBankName($bankName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBankName', array($bankName));

        return parent::setBankName($bankName);
    }

    /**
     * {@inheritDoc}
     */
    public function getBankWebsite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBankWebsite', array());

        return parent::getBankWebsite();
    }

    /**
     * {@inheritDoc}
     */
    public function setBankWebsite($bankWebsite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBankWebsite', array($bankWebsite));

        return parent::setBankWebsite($bankWebsite);
    }

    /**
     * {@inheritDoc}
     */
    public function getBankTax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBankTax', array());

        return parent::getBankTax();
    }

    /**
     * {@inheritDoc}
     */
    public function setBankTax($bankTax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBankTax', array($bankTax));

        return parent::setBankTax($bankTax);
    }

    /**
     * {@inheritDoc}
     */
    public function getBankReturn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBankReturn', array());

        return parent::getBankReturn();
    }

    /**
     * {@inheritDoc}
     */
    public function setBankReturn($bankReturn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBankReturn', array($bankReturn));

        return parent::setBankReturn($bankReturn);
    }

    /**
     * {@inheritDoc}
     */
    public function getBankDirect()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBankDirect', array());

        return parent::getBankDirect();
    }

    /**
     * {@inheritDoc}
     */
    public function setBankDirect($bankDirect)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBankDirect', array($bankDirect));

        return parent::setBankDirect($bankDirect);
    }

}
