<?php

namespace DoctrineORMModule\Proxy\__CG__\Person\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Individual extends \Person\Entity\Individual implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'individualId', 'individualCpf', 'individualRg', 'individualRgDate', 'individualRgOrgan', 'individualRgUf', 'individualBirthDay', 'individualBirthMonth', 'individualBirthYear', 'individualGender', 'individualFather', 'individualMother', 'individualBirthPlace', 'individualBirthUf', 'individualNationality', 'individualStatus', 'occupation', 'professional', 'professionalAddon');
        }

        return array('__isInitialized__', 'individualId', 'individualCpf', 'individualRg', 'individualRgDate', 'individualRgOrgan', 'individualRgUf', 'individualBirthDay', 'individualBirthMonth', 'individualBirthYear', 'individualGender', 'individualFather', 'individualMother', 'individualBirthPlace', 'individualBirthUf', 'individualNationality', 'individualStatus', 'occupation', 'professional', 'professionalAddon');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Individual $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIndividualId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIndividualId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndividualId', array());

        return parent::getIndividualId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndividualId($individualId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndividualId', array($individualId));

        return parent::setIndividualId($individualId);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndividualCpf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndividualCpf', array());

        return parent::getIndividualCpf();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndividualCpf($individualCpf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndividualCpf', array($individualCpf));

        return parent::setIndividualCpf($individualCpf);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndividualRg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndividualRg', array());

        return parent::getIndividualRg();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndividualRg($individualRg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndividualRg', array($individualRg));

        return parent::setIndividualRg($individualRg);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndividualRgDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndividualRgDate', array());

        return parent::getIndividualRgDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndividualRgDate($individualRgDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndividualRgDate', array($individualRgDate));

        return parent::setIndividualRgDate($individualRgDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndividualRgOrgan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndividualRgOrgan', array());

        return parent::getIndividualRgOrgan();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndividualRgOrgan($individualRgOrgan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndividualRgOrgan', array($individualRgOrgan));

        return parent::setIndividualRgOrgan($individualRgOrgan);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndividualRgUf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndividualRgUf', array());

        return parent::getIndividualRgUf();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndividualRgUf($individualRgUf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndividualRgUf', array($individualRgUf));

        return parent::setIndividualRgUf($individualRgUf);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndividualBirthDay()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndividualBirthDay', array());

        return parent::getIndividualBirthDay();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndividualBirthDay($individualBirthDay)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndividualBirthDay', array($individualBirthDay));

        return parent::setIndividualBirthDay($individualBirthDay);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndividualBirthMonth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndividualBirthMonth', array());

        return parent::getIndividualBirthMonth();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndividualBirthMonth($individualBirthMonth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndividualBirthMonth', array($individualBirthMonth));

        return parent::setIndividualBirthMonth($individualBirthMonth);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndividualBirthYear()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndividualBirthYear', array());

        return parent::getIndividualBirthYear();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndividualBirthYear($individualBirthYear)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndividualBirthYear', array($individualBirthYear));

        return parent::setIndividualBirthYear($individualBirthYear);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndividualGender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndividualGender', array());

        return parent::getIndividualGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndividualGender($individualGender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndividualGender', array($individualGender));

        return parent::setIndividualGender($individualGender);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndividualFather()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndividualFather', array());

        return parent::getIndividualFather();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndividualFather($individualFather)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndividualFather', array($individualFather));

        return parent::setIndividualFather($individualFather);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndividualMother()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndividualMother', array());

        return parent::getIndividualMother();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndividualMother($individualMother)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndividualMother', array($individualMother));

        return parent::setIndividualMother($individualMother);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndividualBirthPlace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndividualBirthPlace', array());

        return parent::getIndividualBirthPlace();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndividualBirthPlace($individualBirthPlace)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndividualBirthPlace', array($individualBirthPlace));

        return parent::setIndividualBirthPlace($individualBirthPlace);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndividualBirthUf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndividualBirthUf', array());

        return parent::getIndividualBirthUf();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndividualBirthUf($individualBirthUf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndividualBirthUf', array($individualBirthUf));

        return parent::setIndividualBirthUf($individualBirthUf);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndividualNationality()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndividualNationality', array());

        return parent::getIndividualNationality();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndividualNationality($individualNationality)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndividualNationality', array($individualNationality));

        return parent::setIndividualNationality($individualNationality);
    }

    /**
     * {@inheritDoc}
     */
    public function getOccupation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOccupation', array());

        return parent::getOccupation();
    }

    /**
     * {@inheritDoc}
     */
    public function setOccupation($occupation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOccupation', array($occupation));

        return parent::setOccupation($occupation);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndividualStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndividualStatus', array());

        return parent::getIndividualStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndividualStatus($individualStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndividualStatus', array($individualStatus));

        return parent::setIndividualStatus($individualStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfessionalAddon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfessionalAddon', array());

        return parent::getProfessionalAddon();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfessionalAddon($professionalAddon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfessionalAddon', array($professionalAddon));

        return parent::setProfessionalAddon($professionalAddon);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfessional()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfessional', array());

        return parent::getProfessional();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfessional($professional)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfessional', array($professional));

        return parent::setProfessional($professional);
    }

}
