<?php

namespace DoctrineORMModule\Proxy\__CG__\Customer\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Customer extends \Customer\Entity\Customer implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'customerId', 'customerActive', 'customerTimestamp', 'customerResidenceTime', 'customerResidenceType', 'customerResidenceRentValue', 'customerNotes', 'companyId', 'person', 'statusId', 'customerReference', 'customerPatrimony', 'customerBankAccount', 'sponsor');
        }

        return array('__isInitialized__', 'customerId', 'customerActive', 'customerTimestamp', 'customerResidenceTime', 'customerResidenceType', 'customerResidenceRentValue', 'customerNotes', 'companyId', 'person', 'statusId', 'customerReference', 'customerPatrimony', 'customerBankAccount', 'sponsor');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Customer $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCustomerId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getCustomerId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerId', array());

        return parent::getCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerId($customerId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerId', array($customerId));

        return parent::setCustomerId($customerId);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerActive', array());

        return parent::getCustomerActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerActive($customerActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerActive', array($customerActive));

        return parent::setCustomerActive($customerActive);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerTimestamp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerTimestamp', array());

        return parent::getCustomerTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerTimestamp($customerTimestamp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerTimestamp', array($customerTimestamp));

        return parent::setCustomerTimestamp($customerTimestamp);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyId', array());

        return parent::getCompanyId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyId($companyId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyId', array($companyId));

        return parent::setCompanyId($companyId);
    }

    /**
     * {@inheritDoc}
     */
    public function getPerson()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPerson', array());

        return parent::getPerson();
    }

    /**
     * {@inheritDoc}
     */
    public function setPerson(\Person\Entity\Person $person)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPerson', array($person));

        return parent::setPerson($person);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerName', array());

        return parent::getCustomerName();
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerResidenceTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerResidenceTime', array());

        return parent::getCustomerResidenceTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerResidenceTime($customerResidenceTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerResidenceTime', array($customerResidenceTime));

        return parent::setCustomerResidenceTime($customerResidenceTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerResidenceStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerResidenceStatus', array());

        return parent::getCustomerResidenceStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerResidenceStatus($customerResidenceType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerResidenceStatus', array($customerResidenceType));

        return parent::setCustomerResidenceStatus($customerResidenceType);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerRentValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerRentValue', array());

        return parent::getCustomerRentValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerRentValue($customerResidenceRentValue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerRentValue', array($customerResidenceRentValue));

        return parent::setCustomerRentValue($customerResidenceRentValue);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerStatusId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerStatusId', array());

        return parent::getCustomerStatusId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerStatusId($statusId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerStatusId', array($statusId));

        return parent::setCustomerStatusId($statusId);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerReference()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerReference', array());

        return parent::getCustomerReference();
    }

    /**
     * {@inheritDoc}
     */
    public function addCustomerReference(\Reference\Entity\Reference $reference)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCustomerReference', array($reference));

        return parent::addCustomerReference($reference);
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerReference($customerReference)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerReference', array($customerReference));

        return parent::setCustomerReference($customerReference);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerPatrimony()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerPatrimony', array());

        return parent::getCustomerPatrimony();
    }

    /**
     * {@inheritDoc}
     */
    public function addCustomerPatrimony(\Patrimony\Entity\Patrimony $patrimony)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCustomerPatrimony', array($patrimony));

        return parent::addCustomerPatrimony($patrimony);
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerPatrimony($customerPatrimony)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerPatrimony', array($customerPatrimony));

        return parent::setCustomerPatrimony($customerPatrimony);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerBankAccount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerBankAccount', array());

        return parent::getCustomerBankAccount();
    }

    /**
     * {@inheritDoc}
     */
    public function addCustomerBankAccount(\BankAccount\Entity\BankAccount $bankAccount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCustomerBankAccount', array($bankAccount));

        return parent::addCustomerBankAccount($bankAccount);
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerBankAccount($customerBankAccount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerBankAccount', array($customerBankAccount));

        return parent::setCustomerBankAccount($customerBankAccount);
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerVehicle($customerVehicle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerVehicle', array($customerVehicle));

        return parent::setCustomerVehicle($customerVehicle);
    }

    /**
     * {@inheritDoc}
     */
    public function getSponsor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSponsor', array());

        return parent::getSponsor();
    }

    /**
     * {@inheritDoc}
     */
    public function setSponsor($sponsor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSponsor', array($sponsor));

        return parent::setSponsor($sponsor);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerResidenceType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerResidenceType', array());

        return parent::getCustomerResidenceType();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerResidenceType($customerResidenceType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerResidenceType', array($customerResidenceType));

        return parent::setCustomerResidenceType($customerResidenceType);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerResidenceRentValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerResidenceRentValue', array());

        return parent::getCustomerResidenceRentValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerResidenceRentValue($customerResidenceRentValue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerResidenceRentValue', array($customerResidenceRentValue));

        return parent::setCustomerResidenceRentValue($customerResidenceRentValue);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerNotes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerNotes', array());

        return parent::getCustomerNotes();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerNotes($customerNotes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerNotes', array($customerNotes));

        return parent::setCustomerNotes($customerNotes);
    }

}
