<?php

namespace DoctrineORMModule\Proxy\__CG__\Person\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ProfessionalAddon extends \Person\Entity\ProfessionalAddon implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'professionalAddonId', 'professionalAddonPreviousCompany', 'professionalAddonPreviousPhone', 'professionalAddonPreviousAdmission', 'professionalAddonPreviousDemission', 'professionalAddonPreviousOffice', 'professionalAddonPreviousSalary');
        }

        return array('__isInitialized__', 'professionalAddonId', 'professionalAddonPreviousCompany', 'professionalAddonPreviousPhone', 'professionalAddonPreviousAdmission', 'professionalAddonPreviousDemission', 'professionalAddonPreviousOffice', 'professionalAddonPreviousSalary');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ProfessionalAddon $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getProfessionalAddonId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getProfessionalAddonId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfessionalAddonId', array());

        return parent::getProfessionalAddonId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfessionalAddonId($professionalAddonId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfessionalAddonId', array($professionalAddonId));

        return parent::setProfessionalAddonId($professionalAddonId);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfessionalAddonPreviousCompany()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfessionalAddonPreviousCompany', array());

        return parent::getProfessionalAddonPreviousCompany();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfessionalAddonPreviousCompany($professionalAddonPreviousCompany)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfessionalAddonPreviousCompany', array($professionalAddonPreviousCompany));

        return parent::setProfessionalAddonPreviousCompany($professionalAddonPreviousCompany);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfessionalAddonPreviousPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfessionalAddonPreviousPhone', array());

        return parent::getProfessionalAddonPreviousPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfessionalAddonPreviousPhone($professionalAddonPreviousPhone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfessionalAddonPreviousPhone', array($professionalAddonPreviousPhone));

        return parent::setProfessionalAddonPreviousPhone($professionalAddonPreviousPhone);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfessionalAddonPreviousAdmission()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfessionalAddonPreviousAdmission', array());

        return parent::getProfessionalAddonPreviousAdmission();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfessionalAddonPreviousAdmission($professionalAddonPreviousAdmission)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfessionalAddonPreviousAdmission', array($professionalAddonPreviousAdmission));

        return parent::setProfessionalAddonPreviousAdmission($professionalAddonPreviousAdmission);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfessionalAddonPreviousDemission()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfessionalAddonPreviousDemission', array());

        return parent::getProfessionalAddonPreviousDemission();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfessionalAddonPreviousDemission($professionalAddonPreviousDemission)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfessionalAddonPreviousDemission', array($professionalAddonPreviousDemission));

        return parent::setProfessionalAddonPreviousDemission($professionalAddonPreviousDemission);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfessionalAddonPreviousOffice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfessionalAddonPreviousOffice', array());

        return parent::getProfessionalAddonPreviousOffice();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfessionalAddonPreviousOffice($professionalAddonPreviousOffice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfessionalAddonPreviousOffice', array($professionalAddonPreviousOffice));

        return parent::setProfessionalAddonPreviousOffice($professionalAddonPreviousOffice);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfessionalAddonPreviousSalary()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfessionalAddonPreviousSalary', array());

        return parent::getProfessionalAddonPreviousSalary();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfessionalAddonPreviousSalary($professionalAddonPreviousSalary)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfessionalAddonPreviousSalary', array($professionalAddonPreviousSalary));

        return parent::setProfessionalAddonPreviousSalary($professionalAddonPreviousSalary);
    }

}
