<?php

namespace DoctrineORMModule\Proxy\__CG__\Financial\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Launch extends \Financial\Entity\Launch implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'launchId', 'launchDate', 'launchNumber', 'launchValue', 'launchDescription', 'currentAccountId', 'departmentId', 'accountingItemId');
        }

        return array('__isInitialized__', 'launchId', 'launchDate', 'launchNumber', 'launchValue', 'launchDescription', 'currentAccountId', 'departmentId', 'accountingItemId');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Launch $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getLaunchId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getLaunchId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLaunchId', array());

        return parent::getLaunchId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLaunchId($launchId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLaunchId', array($launchId));

        return parent::setLaunchId($launchId);
    }

    /**
     * {@inheritDoc}
     */
    public function getLaunchDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLaunchDate', array());

        return parent::getLaunchDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setLaunchDate($launchDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLaunchDate', array($launchDate));

        return parent::setLaunchDate($launchDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getLaunchNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLaunchNumber', array());

        return parent::getLaunchNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setLaunchNumber($launchNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLaunchNumber', array($launchNumber));

        return parent::setLaunchNumber($launchNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getLaunchValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLaunchValue', array());

        return parent::getLaunchValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setLaunchValue($launchValue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLaunchValue', array($launchValue));

        return parent::setLaunchValue($launchValue);
    }

    /**
     * {@inheritDoc}
     */
    public function getLaunchDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLaunchDescription', array());

        return parent::getLaunchDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setLaunchDescription($launchDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLaunchDescription', array($launchDescription));

        return parent::setLaunchDescription($launchDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentAccountId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentAccountId', array());

        return parent::getCurrentAccountId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentAccountId($currentAccountId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentAccountId', array($currentAccountId));

        return parent::setCurrentAccountId($currentAccountId);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartmentId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartmentId', array());

        return parent::getDepartmentId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartmentId($departmentId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartmentId', array($departmentId));

        return parent::setDepartmentId($departmentId);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccountingItemId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccountingItemId', array());

        return parent::getAccountingItemId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccountingItemId($accountingItemId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccountingItemId', array($accountingItemId));

        return parent::setAccountingItemId($accountingItemId);
    }

}
