<?php

namespace DoctrineORMModule\Proxy\__CG__\CurrentAccount\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CurrentAccount extends \CurrentAccount\Entity\CurrentAccount implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'currentAccountId', 'currentAccountName', 'currentAccountAgency', 'currentAccountAgencyVd', 'currentAccountAccount', 'currentAccountAccountVd', 'currentAccountManager', 'currentAccountManagerPhone', 'currentAccountManagerEmail', 'currentAccountBankHomePage', 'currentAccountCreditLimit', 'currentAccountCreditExpiration', 'currentAccountOpenDate', 'currentAccountOpenBalance', 'currentAccountHolderCode', 'currentAccountDescription', 'currentAccountClosed', 'currentAccountIsActive', 'bankId', 'companyId', 'currencyId');
        }

        return array('__isInitialized__', 'currentAccountId', 'currentAccountName', 'currentAccountAgency', 'currentAccountAgencyVd', 'currentAccountAccount', 'currentAccountAccountVd', 'currentAccountManager', 'currentAccountManagerPhone', 'currentAccountManagerEmail', 'currentAccountBankHomePage', 'currentAccountCreditLimit', 'currentAccountCreditExpiration', 'currentAccountOpenDate', 'currentAccountOpenBalance', 'currentAccountHolderCode', 'currentAccountDescription', 'currentAccountClosed', 'currentAccountIsActive', 'bankId', 'companyId', 'currencyId');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CurrentAccount $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCurrentAccountId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCurrentAccountId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentAccountId', array());

        return parent::getCurrentAccountId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentAccountId($currentAccountId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentAccountId', array($currentAccountId));

        return parent::setCurrentAccountId($currentAccountId);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentAccountName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentAccountName', array());

        return parent::getCurrentAccountName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentAccountName($currentAccountName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentAccountName', array($currentAccountName));

        return parent::setCurrentAccountName($currentAccountName);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentAccountAgency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentAccountAgency', array());

        return parent::getCurrentAccountAgency();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentAccountAgency($currentAccountAgency)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentAccountAgency', array($currentAccountAgency));

        return parent::setCurrentAccountAgency($currentAccountAgency);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentAccountAccount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentAccountAccount', array());

        return parent::getCurrentAccountAccount();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentAccountAccount($currentAccountAccount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentAccountAccount', array($currentAccountAccount));

        return parent::setCurrentAccountAccount($currentAccountAccount);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentAccountManager()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentAccountManager', array());

        return parent::getCurrentAccountManager();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentAccountManager($currentAccountManager)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentAccountManager', array($currentAccountManager));

        return parent::setCurrentAccountManager($currentAccountManager);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentAccountManagerPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentAccountManagerPhone', array());

        return parent::getCurrentAccountManagerPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentAccountManagerPhone($currentAccountManagerPhone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentAccountManagerPhone', array($currentAccountManagerPhone));

        return parent::setCurrentAccountManagerPhone($currentAccountManagerPhone);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentAccountDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentAccountDescription', array());

        return parent::getCurrentAccountDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentAccountDescription($currentAccountDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentAccountDescription', array($currentAccountDescription));

        return parent::setCurrentAccountDescription($currentAccountDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getBankId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBankId', array());

        return parent::getBankId();
    }

    /**
     * {@inheritDoc}
     */
    public function setBankId($bankId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBankId', array($bankId));

        return parent::setBankId($bankId);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyId', array());

        return parent::getCompanyId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyId($companyId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyId', array($companyId));

        return parent::setCompanyId($companyId);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentAccountAgencyVd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentAccountAgencyVd', array());

        return parent::getCurrentAccountAgencyVd();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentAccountAgencyVd($currentAccountAgencyVd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentAccountAgencyVd', array($currentAccountAgencyVd));

        return parent::setCurrentAccountAgencyVd($currentAccountAgencyVd);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentAccountAccountVd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentAccountAccountVd', array());

        return parent::getCurrentAccountAccountVd();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentAccountAccountVd($currentAccountAccountVd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentAccountAccountVd', array($currentAccountAccountVd));

        return parent::setCurrentAccountAccountVd($currentAccountAccountVd);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentAccountManagerEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentAccountManagerEmail', array());

        return parent::getCurrentAccountManagerEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentAccountManagerEmail($currentAccountManagerEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentAccountManagerEmail', array($currentAccountManagerEmail));

        return parent::setCurrentAccountManagerEmail($currentAccountManagerEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentAccountBankHomePage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentAccountBankHomePage', array());

        return parent::getCurrentAccountBankHomePage();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentAccountBankHomePage($currentAccountBankHomePage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentAccountBankHomePage', array($currentAccountBankHomePage));

        return parent::setCurrentAccountBankHomePage($currentAccountBankHomePage);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentAccountCreditLimit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentAccountCreditLimit', array());

        return parent::getCurrentAccountCreditLimit();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentAccountCreditLimit($currentAccountCreditLimit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentAccountCreditLimit', array($currentAccountCreditLimit));

        return parent::setCurrentAccountCreditLimit($currentAccountCreditLimit);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentAccountCreditExpiration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentAccountCreditExpiration', array());

        return parent::getCurrentAccountCreditExpiration();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentAccountCreditExpiration($currentAccountCreditExpiration)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentAccountCreditExpiration', array($currentAccountCreditExpiration));

        return parent::setCurrentAccountCreditExpiration($currentAccountCreditExpiration);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentAccountOpenDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentAccountOpenDate', array());

        return parent::getCurrentAccountOpenDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentAccountOpenDate($currentAccountOpenDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentAccountOpenDate', array($currentAccountOpenDate));

        return parent::setCurrentAccountOpenDate($currentAccountOpenDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentAccountOpenBalance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentAccountOpenBalance', array());

        return parent::getCurrentAccountOpenBalance();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentAccountOpenBalance($currentAccountOpenBalance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentAccountOpenBalance', array($currentAccountOpenBalance));

        return parent::setCurrentAccountOpenBalance($currentAccountOpenBalance);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentAccountHolderCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentAccountHolderCode', array());

        return parent::getCurrentAccountHolderCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentAccountHolderCode($currentAccountHolderCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentAccountHolderCode', array($currentAccountHolderCode));

        return parent::setCurrentAccountHolderCode($currentAccountHolderCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentAccountClosed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentAccountClosed', array());

        return parent::getCurrentAccountClosed();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentAccountClosed($currentAccountClosed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentAccountClosed', array($currentAccountClosed));

        return parent::setCurrentAccountClosed($currentAccountClosed);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentAccountIsActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentAccountIsActive', array());

        return parent::getCurrentAccountIsActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentAccountIsActive($currentAccountIsActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentAccountIsActive', array($currentAccountIsActive));

        return parent::setCurrentAccountIsActive($currentAccountIsActive);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrencyId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrencyId', array());

        return parent::getCurrencyId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrencyId($currencyId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrencyId', array($currencyId));

        return parent::setCurrencyId($currencyId);
    }

}
