<?php

namespace DoctrineORMModule\Proxy\__CG__\Person\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Professional extends \Person\Entity\Professional implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'professionalId', 'professionalAdmissionDate', 'professionalEnterpriseName', 'professionalEnterpriseCnpj', 'professionalEnterpriseBusiness', 'professionalEnterpriseFoundationDate', 'professionalEnterpriseParticipation', 'professionalEnterprisePartnerCount', 'professionalOffice', 'professionalSalary', 'professionalOtherRevenue', 'professionalBenefitNumber', 'professionalNotes', 'contact', 'address', 'business');
        }

        return array('__isInitialized__', 'professionalId', 'professionalAdmissionDate', 'professionalEnterpriseName', 'professionalEnterpriseCnpj', 'professionalEnterpriseBusiness', 'professionalEnterpriseFoundationDate', 'professionalEnterpriseParticipation', 'professionalEnterprisePartnerCount', 'professionalOffice', 'professionalSalary', 'professionalOtherRevenue', 'professionalBenefitNumber', 'professionalNotes', 'contact', 'address', 'business');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Professional $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getProfessionalId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getProfessionalId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfessionalId', array());

        return parent::getProfessionalId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfessionalId($professionalId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfessionalId', array($professionalId));

        return parent::setProfessionalId($professionalId);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfessionalAdmissionDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfessionalAdmissionDate', array());

        return parent::getProfessionalAdmissionDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfessionalAdmissionDate($professionalAdmissionDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfessionalAdmissionDate', array($professionalAdmissionDate));

        return parent::setProfessionalAdmissionDate($professionalAdmissionDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfessionalEnterpriseName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfessionalEnterpriseName', array());

        return parent::getProfessionalEnterpriseName();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfessionalEnterpriseName($professionalEnterpriseName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfessionalEnterpriseName', array($professionalEnterpriseName));

        return parent::setProfessionalEnterpriseName($professionalEnterpriseName);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfessionalEnterpriseCnpj()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfessionalEnterpriseCnpj', array());

        return parent::getProfessionalEnterpriseCnpj();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfessionalEnterpriseCnpj($professionalEnterpriseCnpj)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfessionalEnterpriseCnpj', array($professionalEnterpriseCnpj));

        return parent::setProfessionalEnterpriseCnpj($professionalEnterpriseCnpj);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfessionalEnterpriseBusiness()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfessionalEnterpriseBusiness', array());

        return parent::getProfessionalEnterpriseBusiness();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfessionalEnterpriseBusiness($professionalEnterpriseBusiness)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfessionalEnterpriseBusiness', array($professionalEnterpriseBusiness));

        return parent::setProfessionalEnterpriseBusiness($professionalEnterpriseBusiness);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfessionalEnterpriseFoundationDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfessionalEnterpriseFoundationDate', array());

        return parent::getProfessionalEnterpriseFoundationDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfessionalEnterpriseFoundationDate($professionalEnterpriseFoundationDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfessionalEnterpriseFoundationDate', array($professionalEnterpriseFoundationDate));

        return parent::setProfessionalEnterpriseFoundationDate($professionalEnterpriseFoundationDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfessionalEnterpriseParticipation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfessionalEnterpriseParticipation', array());

        return parent::getProfessionalEnterpriseParticipation();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfessionalEnterpriseParticipation($professionalEnterpriseParticipation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfessionalEnterpriseParticipation', array($professionalEnterpriseParticipation));

        return parent::setProfessionalEnterpriseParticipation($professionalEnterpriseParticipation);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfessionalEnterprisePartnerCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfessionalEnterprisePartnerCount', array());

        return parent::getProfessionalEnterprisePartnerCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfessionalEnterprisePartnerCount($professionalEnterprisePartnerCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfessionalEnterprisePartnerCount', array($professionalEnterprisePartnerCount));

        return parent::setProfessionalEnterprisePartnerCount($professionalEnterprisePartnerCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfessionalOffice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfessionalOffice', array());

        return parent::getProfessionalOffice();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfessionalOffice($professionalOffice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfessionalOffice', array($professionalOffice));

        return parent::setProfessionalOffice($professionalOffice);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfessionalSalary()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfessionalSalary', array());

        return parent::getProfessionalSalary();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfessionalSalary($professionalSalary)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfessionalSalary', array($professionalSalary));

        return parent::setProfessionalSalary($professionalSalary);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfessionalOtherRevenue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfessionalOtherRevenue', array());

        return parent::getProfessionalOtherRevenue();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfessionalOtherRevenue($professionalOtherRevenue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfessionalOtherRevenue', array($professionalOtherRevenue));

        return parent::setProfessionalOtherRevenue($professionalOtherRevenue);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfessionalBenefitNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfessionalBenefitNumber', array());

        return parent::getProfessionalBenefitNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfessionalBenefitNumber($professionalBenefitNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfessionalBenefitNumber', array($professionalBenefitNumber));

        return parent::setProfessionalBenefitNumber($professionalBenefitNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfessionalNotes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfessionalNotes', array());

        return parent::getProfessionalNotes();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfessionalNotes($professionalNotes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfessionalNotes', array($professionalNotes));

        return parent::setProfessionalNotes($professionalNotes);
    }

    /**
     * {@inheritDoc}
     */
    public function getContact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContact', array());

        return parent::getContact();
    }

    /**
     * {@inheritDoc}
     */
    public function setContact($contact)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContact', array($contact));

        return parent::setContact($contact);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', array());

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', array($address));

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getBusiness()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBusiness', array());

        return parent::getBusiness();
    }

    /**
     * {@inheritDoc}
     */
    public function setBusiness($business)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBusiness', array($business));

        return parent::setBusiness($business);
    }

}
