<?php
$title = $this->translate('Receitas');
$this->headTitle($title);
?>
<div class="row">
    <div class="col-md-6">
        <h1 class="container-header"><i class="glyphicon glyphicon-download-alt"></i> <?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="col-md-6">
        <div class="btn-group btn-group-sm pull-right">
            <a class="btn btn-default" href="<?php echo $this->url('admin/financial/revenue/add', array('action' => 'add')); ?>"> <i class="glyphicon glyphicon-plus"></i> <?php echo $this->translate('Nova Receita'); ?></a>
        </div>
    </div> 
</div>
<div class="row">
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title"><i class="glyphicon glyphicon-usd"></i> Total de Receita</h4>
            </div>
            <div class="panel-body" dir="rtl">
                <h3 class="text-success"><?php echo $this->currency((double) $this->total['total']); ?></h4>
            </div>
        </div>
    </div>

    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title"><i class="glyphicon glyphicon-download-alt"></i> Receitas</h4>
            </div>
            <table class="table table-striped table-condensed">
                <tr>
                    <th class="col-md-2"><?php echo $this->translate('DATA'); ?></th>
                    <th class=""><?php echo $this->translate('NÚMERO'); ?></th>
                    <th class=""><?php echo $this->translate('DESCRIÇÃO'); ?></th>
                    <th class=""><?php echo $this->translate('FAVORECIDO'); ?></th>
                    <th class="col-md-2" colspan="10"><?php echo $this->translate('VALOR'); ?></th>
                </tr>
                <?php if (0 == count($this->revenue)): ?>
                    <tr>
                        <td colspan="10" class="alert alert-info text-center"><?php echo $this->translate('Não há receitas até o momento.') ?></td>
                    </tr>
                <?php else: ?>
                    <?php foreach ($this->revenue as $revenue) : ?>
                        <tr>
                            <td><?php echo $this->date($revenue->getLaunch()->getLaunchDate()); ?></td>
                            <td><?php echo $this->escapeHtml($revenue->getLaunch()->getLaunchNumber()); ?></td>
                            <td><?php echo $this->escapeHtml($revenue->getLaunch()->getLaunchDescription()); ?></td>
                            <td><?php echo $this->escapeHtml($revenue->getCustomerId()->getPerson()->getPersonName()); ?></td>
                            <td><?php echo $this->currency($revenue->getLaunch()->getLaunchValue()); ?></td>
                            <td>
                                <div class="btn-group btn-group-xs pull-right">
                                    <a class="btn btn-default" href="<?php echo $this->url('admin/financial/revenue/edit', array('action' => 'edit', 'id' => $revenue->getRevenueId()))
                        ?>"><i class="glyphicon glyphicon-edit"></i></a>
                                    <a class="btn btn-default" href="<?php echo $this->url('admin/financial/revenue/delete', array('action' => 'delete', 'id' => $revenue->getRevenueId()))
                        ?>"><i class="glyphicon glyphicon-remove"></i></a>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
                </tbody>
            </table>
            <div class="panel-footer">
                <?php
                $paginationInfo = $this->placeholder('pagination');
                if (!isset($paginationInfo->route)) {
                    $paginationInfo->route = 'admin/financial/revenue';
                    $paginationInfo->params = array();
                }
                ?>
                <?php echo $this->paginationControl($this->revenue, 'Sliding', 'layout/pagination'); ?>
            </div>
        </div>
    </div>
</div>