<?php
$title = $this->translate('Editar Categoria');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin/category/edit', array('id' => $this->id)));
$form->prepare();
?>
<?php echo $this->form()->openTag($form); ?>
<div class="controls">
    <?php $category = $form->get('category'); ?>
    <?php echo $this->formHidden($category->get('categoryId')); ?>
    <div class="controls-row">
        <?php echo $this->formSelect($category->get('categorySelf')); ?>
    </div>
    <div class="controls-row">
        <?php echo $this->formText($category->get('categoryName')); ?>
    </div>
    <label>Defina qual o tipo desta categoria:</label>
    <div class="controls-row">
        <label class="radio">
            <?php echo $this->formRadio($category->get('categoryIsService')); ?>
        </label>
    </div>
</div>
<div class="form-actions">
    <?php echo $this->formHidden($form->get('security')); ?>
    <?php echo $this->formElement($form->get('submit')); ?>
    <?php echo $this->formElement($form->get('cancel')); ?>
</div>
<?php echo $this->form()->closeTag(); ?>