<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Dartalla ' . $this->translate('1.0'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/application.css')
                ->prependStylesheet($this->basePath() . '/css/jquery-ui/smoothness/jquery-ui-1.10.3.custom.min.css')
                ->prependStylesheet($this->basePath() . '/font-awesome/css/font-awesome.min.css')
//                ->prependStylesheet($this->basePath() . '/bootstrap/css/bootstrap-theme.css')
                ->prependStylesheet($this->basePath() . '/bootstrap/css/bootstrap.min.css')
        ?>
        <!--[if IE 7]>
            <link rel="stylesheet" href="/font-awesome/css/font-awesome-ie7.min.css">
        <![endif]-->
        <!--[if lte IE 8]><script language="javascript" type="text/javascript" src="/js/excanvas.min.js"></script><![endif]-->
        <?php
        echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/application.js')
                ->prependFile($this->basePath() . '/js/jquery.price.js')
                ->prependFile($this->basePath() . '/js/jquery-masked.js')
                ->prependFile($this->basePath() . '/js/highcharts.js')
                ->prependFile($this->basePath() . '/bootstrap/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.ui.datepicker-pt-BR.js')
                ->prependFile($this->basePath() . '/js/jquery-ui.min.js')
                ->prependFile($this->basePath() . '/js/jquery-2.0.3.min.js')
        ?>
    </head>
    <body>
        <?= $this->partial('layout/menu'); ?>
        <?php
        echo $this->navigation('admin_navigation')
                ->breadcrumbs()
                ->setSeparator(' / ')
                ->setMinDepth(0)
                ->setLinkLast(false)
                ->setPartial('layout/breadcrumbs');
        ?>
        <?php if ($this->zfcUserIdentity() !== false): ?>
            <div class="container full-width">
                <div class="row">
                    <div class="col-md-12">
                        <?php echo $this->content; ?>
                        <?php echo $this->inlineScript(); ?>                
                    </div>
                </div>
            </div>
        <?php else: ?>
            <div class="container">
                <?php echo $this->content; ?>
            </div>
        <?php endif; ?>
    </body>
</html>
