<?php
$title = $this->translate('Editar Moeda');
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('admin/currency/edit', array('id' => $this->id)));
$form->prepare();
?>
<h1 class="container-header"><i class="glyphicon glyphicon-flag"></i> <?php echo $this->escapeHtml($title); ?></h1>
<?php echo $this->form()->openTag($form); ?>
<div class="form-group">
    <?php $currency = $form->get('currency'); ?>
    <?php echo $this->formHidden($currency->get('currencyId')); ?>

    <div class="row">
        <div class="col-md-4">
            <?php echo $this->formLabel($currency->get('currencyName')); ?>
            <?php echo $this->formText($currency->get('currencyName')); ?>
        </div>
    </div>
</div>
<?php echo $this->formHidden($form->get('security')); ?>
<div class="btn-group">
    <?php echo $this->formElement($form->get('submit')); ?>
    <?php echo $this->formElement($form->get('cancel')); ?>
</div>
<?php echo $this->form()->closeTag(); ?>
