<?php
$title = $this->translate('Apagar Serviço');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p><?php echo $this->translate('Você tem certeza de que deseja apagar ')?>
    '<?php echo $this->escapeHtml($this->service->getServiceName()); ?>'?
</p>
<?php
$url = $this->url('admin/service/delete', array(
    'action' => 'delete',
    'id'     => $this->id,
));

?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo $this->service->getServiceId(); ?>" />
    <div class="form-actions">
	    <input  type="submit" name="del" value="Sim" class="btn btn-primary" />
	    <input type="submit" name="del" value="Não" class="btn" />
    </div>
</div>
</form>
