<?php
$title = $this->translate('Apagar Empresa');
$this->headTitle($title);

$url = $this->url('admin/company/delete', array(
    'action' => 'delete',
    'id' => $this->company_id,
        ));
?>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="panel-title"><i class="glyphicon glyphicon-barcode"></i> <?php echo $this->escapeHtml($title); ?></div>
    </div>
    <div class="panel-body">
        <blockquote>
            <p><?php echo $this->translate('Você tem certeza de que deseja apagar ') ?>
                '<?php echo $this->escapeHtml($this->company->getCompanyName()); ?>'?
            </p>
        </blockquote>
        <form action="<?php echo $url; ?>" method="post">
            <div>
                <input type="hidden" name="id" value="<?php echo $this->company->getCompanyId(); ?>" />
                <div class="btn-group">
                    <input  type="submit" name="del" value="Sim" class="btn btn-primary" />
                    <input type="submit" name="del" value="Não" class="btn btn-default" />
                </div>
            </div>
        </form>
    </div>
</div>
