<?php
$title = $this->translate('Adicionar Cargo');
$this->headTitle($title);
$form = $this->form;
$form->prepare();
?>
<h1 class="container-header"><i class="fa fa-male"></i> <?php echo $this->escapeHtml($title); ?></h1>
<?php echo $this->form()->openTag($form); ?>
<div class="form-group">
    <?php $office = $form->get('office'); ?>
    <?php echo $this->formRow($office->get('officeId')); ?>
    <div class="row">
        <div class="col-md-4">
            <?php echo $this->formLabel($office->get('officeName')); ?>
            <?php echo $this->formText($office->get('officeName')); ?>
        </div>
    </div>
</div>
<?php echo $this->formHidden($form->get('security')); ?>
<div class="btn-group">
    <?php echo $this->formElement($form->get('submit')); ?>
    <?php echo $this->formElement($form->get('cancel')); ?>
</div>
<?php echo $this->form()->closeTag(); ?>
