<?php
$title = $this->translate('Cargos');
$this->headTitle($title);
?>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-6">
                <h2 class="panel-title"><i class="fa fa-male"></i> <?php echo $this->escapeHtml($title); ?></h2>
            </div>
            <div class="col-md-6">
                <div class="btn-group btn-group-sm pull-right">
                    <a class="btn btn-default" href="<?php echo $this->url('admin/office/add', array('action' => 'add')); ?>"> <i class="glyphicon glyphicon-plus"></i> <?php echo $this->translate('Novo'); ?></a>
                </div>
            </div> 
        </div>
    </div>
    <table class="table table-condensed table-hover">
        <tr>
            <th class="" colspan="10"><?php echo $this->translate('CARGO'); ?></th>
        </tr>
        <?php if (0 == count($this->office)): ?>
            <tr>
                <td colspan="10" class="alert alert-info text-center"><?php echo $this->translate('Não há registros no banco de dados.') ?></td>
            </tr>
        <?php else: ?>
            <?php foreach ($this->office as $office) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($office->getOfficeName()); ?></td>
                    <td>
                        <div class="btn-group btn-group-xs pull-right">
                            <a class="btn btn-default" href="<?php echo $this->url('admin/office/edit', array('action' => 'edit', 'id' => $office->getOfficeId()))
                ?>"><i class="glyphicon glyphicon-edit"></i></a>
                            <a class="btn btn-default" href="<?php echo $this->url('admin/office/delete', array('action' => 'delete', 'id' => $office->getOfficeId()))
                ?>"><i class="glyphicon glyphicon-remove"></i></a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
        </tbody>
    </table>
    <div class="panel-footer">
        <?php
        $paginationInfo = $this->placeholder('pagination');
        if (!isset($paginationInfo->route)) {
            $paginationInfo->route = 'admin/office';
            $paginationInfo->params = array();
        }
        ?>
        <?php echo $this->paginationControl($this->office, 'Sliding', 'layout/pagination'); ?>
    </div>
</div>
