<?php
$title = $this->translate('Editar Forma de Pagamento');
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('admin/payment-type/edit', array('id' => $this->id)));
$form->prepare();
?>
<h2 class="container-header"><i class="fa fa-money"></i> <?php echo $this->escapeHtml($title); ?></h2>
<?php echo $this->form()->openTag($form); ?>
<div class="form-group">
    <div class="row">
        <?php $paymentType = $form->get('paymentType'); ?>
        <?php echo $this->formHidden($paymentType->get('paymentTypeId')); ?>
        <?php echo $this->formHidden($paymentType->get('companyId')->setValue($this->companyAuth()->getCompanyId())); ?>
        <div class="col-lg-4">
            <?php echo $this->formLabel($paymentType->get('paymentTypeName')); ?>
            <?php echo $this->formText($paymentType->get('paymentTypeName')); ?>
        </div>
    </div>
    <?php echo $this->formHidden($form->get('security')); ?>
</div>
<div class="btn-group">
    <?php echo $this->formElement($form->get('submit')); ?>
    <?php echo $this->formElement($form->get('cancel')); ?>
</div>
<?php echo $this->form()->closeTag(); ?>
