<?php
$title = $this->translate('Editar Item Contábil');
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('admin/accounting-item/edit', array('id' => $this->id)));
$form->prepare();
?>
<h1 class="container-header"><i class="glyphicon glyphicon-gift"></i> <?php echo $this->escapeHtml($title); ?></h1>
<?php echo $this->form()->openTag($form); ?>
<div class="form-group">
    <?php $accountingItem = $form->get('accountingItem'); ?>
    <?php echo $this->formHidden($accountingItem->get('accountingItemId')); ?>
    <?php echo $this->formHidden($accountingItem->get('companyId')->setValue($this->companyAuth()->getCompanyId())); ?>
    <div class="row">
        <div class="col-md-4">
            <?php echo $this->formLabel($accountingItem->get('accountingItemName')); ?>
            <?php echo $this->formText($accountingItem->get('accountingItemName')); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <?php echo $this->formRadio($accountingItem->get('accountingItemType')->setLabelAttributes(array('class' => 'radio'))); ?>
        </div>
    </div>
</div>
<?php echo $this->formHidden($form->get('security')); ?>
<div class="btn-group">
    <?php echo $this->formElement($form->get('submit')); ?>
    <?php echo $this->formElement($form->get('cancel')); ?>
</div>
<?php echo $this->form()->closeTag(); ?>
