<?php
$title = $this->translate('Item Contábil');
$this->headTitle($title);
?>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-6">
                <h4 class="panel-title"><i class="glyphicon glyphicon-gift"></i> <?php echo $this->escapeHtml($title); ?></h4>
            </div>
            <div class="col-md-6">
                <div class="btn-group btn-group-sm pull-right">
                    <a class="btn btn-default" href="<?php echo $this->url('admin/accounting-item/add', array('action' => 'add')); ?>"> <i class="glyphicon glyphicon-plus"></i> <?php echo $this->translate('Novo'); ?></a>
                </div>
            </div>
        </div>
    </div>
    <table class="table table-condensed table-hover">
        <tr>
            <th><?php echo $this->translate('ÍTEM CONTÁBIL'); ?></th>
            <th colspan="10"><?php echo $this->translate('TIPO'); ?></th>
        </tr>
        <?php if (0 == count($this->accountingItem)): ?>
            <tr>
                <td colspan="10" class="alert alert-info text-center"><?php echo $this->translate('Não há registros no banco de dados.') ?></td>
            </tr>
        <?php else: ?>
            <?php foreach ($this->accountingItem as $accountingItem) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($accountingItem->getAccountingItemName()); ?></td>
                    <?php if ($accountingItem->getAccountingItemType()): ?>
                        <td><span class="label label-success"><?php echo $this->translate('ITEM DE ENTRADA'); ?></span></td>
                    <?php else: ?>
                        <td><span class="label label-danger"><?php echo $this->translate('ITEM DE SAÍDA'); ?></span></td>
                    <?php endif; ?>
                    <td>
                        <div class="btn-group btn-group-xs pull-right">
                            <a class="btn btn-default" href="<?php echo $this->url('admin/accounting-item/edit', array('action' => 'edit', 'id' => $accountingItem->getAccountingItemId()))
                    ?>"><i class="glyphicon glyphicon-edit"></i></a>
                            <a class="btn btn-default" href="<?php echo $this->url('admin/accounting-item/delete', array('action' => 'delete', 'id' => $accountingItem->getAccountingItemId()))
                    ?>"><i class="glyphicon glyphicon-remove"></i></a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </table>
    <div class="panel-footer">
        <?php
        $paginationInfo = $this->placeholder('pagination');
        if (!isset($paginationInfo->route)) {
            $paginationInfo->route = 'admin/accounting-item';
            $paginationInfo->params = array();
        }
        ?>
        <?php echo $this->paginationControl($this->accountingItem, 'Sliding', 'layout/pagination'); ?>
    </div>
</div>
