<?php
$title = $this->translate('Novo Vendedor');
$this->headTitle($title);
?>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin/seller/add', array(
            'action' => 'add',
            'id' => $this->shopmanId,
            'type' => $this->personType)));
$form->prepare();
?>
<h2><i class="glyphicon glyphicon-user"></i> <?php echo $this->escapeHtml($title); ?></h2>
<?php echo $this->form()->openTag($form); ?>
<?php $employee = $form->get('seller'); ?>
<div class="tabbable">
    <ul class="nav nav-tabs">
        <li class="active">
            <a href="#tab0" data-toggle="tab"><?php echo $this->translate('Lista de Vendedores'); ?></a>
        </li>
        <li>
            <a href="#tab1" data-toggle="tab"><?php echo $this->translate('Dados Gerais'); ?></a>
        </li>
        <li>
            <a href="#tab2" data-toggle="tab"><?php echo $this->translate('Dados Pessoais'); ?></a>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="tab0">
            <table class="table table-condensed table-hover">
                <tr>
                    <th class=""><?php echo $this->translate('VENDEDOR'); ?></th>
                    <th class=""><?php echo $this->translate('CIDADE'); ?></th>
                    <th class="col-md-2"><?php echo $this->translate('TELEFONE'); ?></th>
                    <th class="col-md-2"><?php echo $this->translate('CELULAR'); ?></th>
                    <th class="col-md-2"><?php echo $this->translate(''); ?></th>
                </tr>
                <?php if (0 == count($this->shopmanSeller)): ?>
                    <tr>
                        <td colspan="10" class="alert alert-info text-center"><?php echo $this->translate('Não há nenhum registro no banco de dados.') ?></td>
                    </tr>
                <?php else: ?>
                    <?php foreach ($this->shopmanSeller as $shopmanSeller) : ?>
                        <tr>
                            <td><?php echo $this->escapeHtml($shopmanSeller->getPerson()->getPersonName()); ?></td>
                            <td><?php echo $this->escapeHtml($shopmanSeller->getPerson()->getAddress()->getAddressName()); ?></td>
                            <td><?php echo $this->escapeHtml($this->phone($shopmanSeller->getPerson()->getContact()->getContactPhone())); ?></td>
                            <td><?php echo $this->escapeHtml($this->phone($shopmanSeller->getPerson()->getContact()->getContactCell())); ?></td>
                            <td>
                                <div class="btn-group btn-group-xs pull-right">
                                    <a class="btn btn-default" href="<?php
                                    echo $this->url('admin/seller/view', array('action' => 'view',
                                        'id' => $shopmanSeller->getSellerId()));
                                    ?>"><i class="glyphicon glyphicon-folder-open"></i></a>
                                    <a class="btn btn-default" href="<?php
                                    echo $this->url('admin/seller/edit', array('action' => 'edit',
                                        'id' => $shopmanSeller->getSellerId(), 'type' => base64_encode($shopmanSeller->getPerson()->getPersonType())));
                                    ?>"><i class="glyphicon glyphicon-edit"></i></a>
                                    <a class="btn btn-default" href="<?php
                                    echo $this->url('admin/seller/delete', array('action' => 'delete',
                                        'id' => $shopmanSeller->getSellerId()));
                                    ?>"><i class="glyphicon glyphicon-remove"></i></a>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
            </table>
        </div>
        <div class="tab-pane" id="tab1">
            <?php $person = $employee->get('person'); ?>
            <?php echo $this->personForm($person); ?>
        </div>
        <div class="tab-pane" id="tab2">
            <?php if ($this->personType == base64_encode(1)): ?>
                <?php $legal = $person->get('legal'); ?>
                <?php echo $this->legalForm($legal); ?>
            <?php elseif ($this->personType == base64_encode(0)): ?>
                <?php $individual = $person->get('individual'); ?>
                <?php echo $this->individualForm($individual); ?>
            <?php endif; ?>
        </div>
    </div>
</div>
<?php echo $this->formRow($form->get('security')); ?>
<div class="btn-group">
    <?php echo $this->formSubmit($form->get('submit')); ?>
    <?php echo $this->formRow($form->get('cancel')); ?>
</div>
<?php echo $this->form()->closeTag(); ?>