<?php
$title = $this->translate('Editar Vendedor');
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url(
                'admin/seller/edit', array(
            'action' => 'edit',
            'id' => $this->id,
            'type' => $this->personType)
));
$form->prepare();
?>
<h2><i class="glyphicon glyphicon-user"></i> <?php echo $this->escapeHtml($title); ?></h2>
<?php echo $this->form()->openTag($form); ?>
<?php $employee = $form->get('seller'); ?>
<div class="tabbable">
    <ul class="nav nav-tabs">
        <li class="active">
            <a href="#tab1" data-toggle="tab"><?php echo $this->translate('Dados Gerais'); ?></a>
        </li>
        <li>
            <a href="#tab2" data-toggle="tab"><?php echo $this->translate('Dados Pessoais'); ?></a>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="tab1">
            <?php $person = $employee->get('person'); ?>
            <?php echo $this->personForm($person); ?>
        </div>
        <div class="tab-pane" id="tab2">
            <?php if ($this->personType == base64_encode(1)): ?>
                <?php $legal = $person->get('legal'); ?>
                <?php echo $this->legalForm($legal); ?>
            <?php elseif ($this->personType == base64_encode(0)): ?>
                <?php $individual = $person->get('individual'); ?>
                <?php echo $this->individualForm($individual); ?>
            <?php endif; ?>
        </div>
    </div>
</div>
<?php echo $this->formRow($form->get('security')); ?>
<div class="btn-group">
    <?php echo $this->formSubmit($form->get('submit')); ?>
    <?php echo $this->formRow($form->get('cancel')); ?>
</div>
<?php echo $this->form()->closeTag(); ?>