<div class='panel panel-warning'>
    <div class="panel-heading">
        <h1 class="panel-title"><i class="fa fa-truck"></i> Lista de Veículos do Cliente</h1>
    </div>
    <table class="table">
        <tr>
            <th class=""><?php echo $this->translate('MARCA'); ?></th>
            <th class=""><?php echo $this->translate('MODELO'); ?></th>
            <th class=""><?php echo $this->translate('VERSÃO'); ?></th>
            <th class=""><?php echo $this->translate('ANO/MODELO'); ?></th>
            <th class=""><?php echo $this->translate('PLACA'); ?></th>
            <th class=""><?php echo $this->translate('COR'); ?></th>
            <th class=""><?php echo $this->translate('VALOR'); ?></th>
            <th class=""><?php echo $this->translate('AÇÕES'); ?></th>
        </tr>
        <?php if (0 == count($this->customerVehicle)): ?>
            <tr class="alert alert-info">
                <td colspan="10" class="alert alert-info text-center"><?php echo $this->translate('Nenhum registro encontrado.') ?></td>
            </tr>
        <?php else: ?>
            <?php foreach ($this->customerVehicle as $customerVehicle) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($customerVehicle->getVehicleBrandId()->getVehicleBrandName()); ?></td>
                    <td><?php echo $this->escapeHtml($customerVehicle->getVehicleModelId()->getVehicleModelName()); ?></td>
                    <td><?php echo $this->escapeHtml($customerVehicle->getVehicleVersionId()->getVehicleVersionName()); ?></td>
                    <td>
                        <?php echo $customerVehicle->getVehicleYear(); ?>
                        <?php echo ($customerVehicle->getVehicleYearModel()) ? " / " . $customerVehicle->getVehicleYearModel() : ""; ?>
                    </td>
                    <td><?php echo $this->escapeHtml($customerVehicle->getVehiclePlate()); ?></td>
                    <td><?php echo $this->escapeHtml($customerVehicle->getVehicleColor()); ?></td>
                    <td><?php echo $this->currency($customerVehicle->getVehicleValue()); ?></td>
                    <td>
                        <div class="btn-group btn-group-xs pull-right">
                            <a class="btn btn-default btn-xs" href="javascript: customerVehicleDelete('<?php echo $customerVehicle->getVehicleId(); ?>', '<?php echo $this->customerId; ?>')"><i class="glyphicon glyphicon-remove"></i></a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </table>
</div>