<div class="panel panel-warning">
    <div class="panel-heading">
        <h1 class="panel-title"><i class="fa fa-building"></i> Lista de Patrimônio</h1>
    </div>
    <table class="table table-condensed table-hover">
        <tr>
            <th class=""><?php echo $this->translate('PATRIMONIO'); ?></th>
            <th class="" colspan="2"><?php echo $this->translate('VALOR'); ?></th>
        </tr>
        <?php if (0 == count($this->customerPatrimony)): ?>
            <tr class="alert alert-info">
                <td colspan="10" class="alert alert-info text-center"><?php echo $this->translate('Nenhum registro encontrado.') ?></td>
            </tr>
        <?php else: ?>
            <?php foreach ($this->customerPatrimony as $customerPatrimony) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($customerPatrimony->getPatrimonyName()); ?></td>
                    <td><?php echo $this->currency($customerPatrimony->getPatrimonyValue()); ?></td>
                    <td>
                        <div class="btn-group btn-group-xs pull-right">
                            <a class="btn btn-default" href="javascript: customerPatrimonyDelete('<?php echo $customerPatrimony->getPatrimonyId(); ?>', '<?php echo $this->customerId; ?>')"><i class="glyphicon glyphicon-remove"></i></a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </table>
</div>