<?php
$title = $this->translate('Adicionar Tipo de Documento');
$this->headTitle($title);
$form = $this->form;
$form->prepare();
?>
<h1 class="container-header"><i class="fa fa-file-text"></i> <?php echo $this->escapeHtml($title); ?></h1>
<?php echo $this->form()->openTag($form); ?>
<div class="form-group">
    <?php $documentType = $form->get('documentType'); ?>
    <?php echo $this->formHidden($documentType->get('documentTypeId')); ?>
    <?php echo $this->formHidden($documentType->get('company')->setValue($this->companyAuth()->getCompanyId())); ?>
    <div class="row">
        <div class="col-md-4">
            <?php echo $this->formLabel($documentType->get('documentTypeName')); ?>
            <?php echo $this->formText($documentType->get('documentTypeName')); ?>
        </div>
    </div>
</div>
<?php echo $this->formHidden($form->get('security')); ?>
<div class="btn-group">
    <?php echo $this->formElement($form->get('submit')); ?>
    <?php echo $this->formElement($form->get('cancel')); ?>
</div>
<?php echo $this->form()->closeTag(); ?>
