<?php
$title = $this->translate('Referências do Cliente');
$this->headTitle($title);
$form = $this->form;
$form->prepare();
?>
<legend><h2><i class="glyphicon glyphicon-thumbs-up"></i> <?php echo $this->escapeHtml($title); ?></h2></legend>
<div class="row">
    <div class="col-md-4">
        <?php echo $this->form()->openTag($form); ?>
        <?php $customerReference = $form->get('customerReference'); ?>
        <div class="form-group">
            <?php echo $this->formLabel($customerReference->get('customerId')); ?>
            <?php echo $this->formSelect($customerReference->get('customerId')); ?>
            
            <?php $reference = $customerReference->get('reference'); ?>
            
            <?php echo $this->formLabel($reference->get('referenceType')); ?>
            <?php echo $this->formSelect($reference->get('referenceType')); ?>

            <?php echo $this->formLabel($reference->get('referenceName')); ?>
            <?php echo $this->formText($reference->get('referenceName')); ?>

            <?php echo $this->formLabel($reference->get('referencePhone')); ?>
            <?php echo $this->formText($reference->get('referencePhone')); ?>
        </div>
        <?php echo $this->formHidden($form->get('security')); ?>
        <div class="btn-group">
            <?php echo $this->formElement($form->get('submit')); ?>
            <?php echo $this->formElement($form->get('cancel')); ?>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
    <div class="col-md-8">
        <div class="customer-reference-list"></div>
    </div>
</div>
<script type="text/javascript">
    customerReferenceList('<?php echo $this->customerId?>');
</script>