<div class="panel panel-warning">
    <div class="panel-heading">
        <h1 class="panel-title"><i class="glyphicon glyphicon-thumbs-up"></i> Lista de Referência</h1>
    </div>
    <table class="table table-condensed table-hover">
        <tr>
            <th class=""><?php echo $this->translate('TIPO'); ?></th>
            <th class=""><?php echo $this->translate('REFERÊNCIA'); ?></th>
            <th class="" colspan="2"><?php echo $this->translate('TELEFONE'); ?></th>
        </tr>
        <?php if (0 == count($this->customerReference)): ?>
            <tr class="alert alert-info">
                <td colspan="10" class="alert alert-info text-center"><?php echo $this->translate('Nenhum registro encontrado.') ?></td>
            </tr>
        <?php else: ?>
            <?php foreach ($this->customerReference as $customerReference) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($customerReference->getReferenceType()); ?></td>
                    <td><?php echo $this->escapeHtml($customerReference->getReferenceName()); ?></td>
                    <td><?php echo $this->phone($customerReference->getReferencePhone()); ?></td>
                    <td>
                        <div class="btn-group btn-group-xs pull-right">
                            <a class="btn btn-default" href="javascript: customerReferenceDelete('<?php echo $customerReference->getReferenceId(); ?>', '<?php echo $this->customerId; ?>')"><i class="glyphicon glyphicon-remove"></i></a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </table>
</div>