<?php
$title = $this->translate('Editar Avalista / Cônjuge');
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url(
                'admin/sponsor/edit', array(
            'action' => 'edit',
            'id' => $this->id,
            'type' => $this->personType)
));
$form->prepare();
?>
<h2 class="container-header"><i class="glyphicon glyphicon-user"></i> <?php echo $this->escapeHtml($title); ?></h2>
<?php echo $this->form()->openTag($form); ?>
<?php $sponsor = $form->get('sponsor'); ?>
<div class="tabbable">
    <ul class="nav nav-tabs">
        <li class="active">
            <a href="#tab1" data-toggle="tab"><?php echo $this->translate('Dados Gerais'); ?></a>
        </li>
        <li>
            <a href="#tab2" data-toggle="tab"><?php echo $this->translate('Dados Complementares'); ?></a>
        </li>
        <?php if ($this->personType == base64_encode(0)): ?>
            <li>
                <a href="#tab3" data-toggle="tab"><?php echo $this->translate('Dados Profissionais'); ?></a>
            </li>
            <li>
                <a href="#tab4" data-toggle="tab"><?php echo $this->translate('Dados Profissionais Adicionais'); ?></a>
            </li>
        <?php endif; ?>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="tab1">
            <?php echo $this->formHidden($sponsor->get('companyId')->setValue($this->companyAuth()->getCompanyId())); ?>
            <?php $person = $sponsor->get('person'); ?>
            <?php echo $this->personForm($person); ?>
        </div>
        <?php if ($this->personType == base64_encode(1)): ?>
            <div class="tab-pane" id="tab2">
                <?php $legal = $person->get('legal'); ?>
                <?php echo $this->legalForm($legal); ?>
            </div>
        <?php elseif ($this->personType == base64_encode(0)): ?>
            <div class="tab-pane" id="tab2">
                <?php $individual = $person->get('individual'); ?>
                <?php echo $this->individualForm($individual); ?>
            </div>
            <div class="tab-pane" id="tab3">
                <?php $professional = $individual->get('professional'); ?>
                <?php echo $this->professionalForm($professional); ?>
            </div>
            <div class="tab-pane" id="tab4">
                <?php $professional_addon = $individual->get('professionalAddon'); ?>
                <?php echo $this->professionalAddonForm($professional_addon); ?>
            </div>
        <?php endif; ?>
    </div>
</div>
<?php echo $this->formRow($form->get('security')); ?>
<div class="btn-group">
    <?php echo $this->formSubmit($form->get('submit')); ?>
    <?php echo $this->formRow($form->get('cancel')); ?>
</div>
<?php echo $this->form()->closeTag(); ?>