<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Company\Module'                           => __DIR__ . '/Module.php',
    'Company\Controller\CompanyController'     => __DIR__ . '/src/Company/Controller/CompanyController.php',
    'Company\Controller\Plugin\CompanySession' => __DIR__ . '/src/Company/Controller/Plugin/CompanySession.php',
    'Company\Entity\Company'                   => __DIR__ . '/src/Company/Entity/Company.php',
    'Company\Factory\CompanyControllerFactory' => __DIR__ . '/src/Company/Factory/CompanyControllerFactory.php',
    'Company\Form\Company'                     => __DIR__ . '/src/Company/Form/Company.php',
    'Company\Form\Fieldset\Company'            => __DIR__ . '/src/Company/Form/Fieldset/Company.php',
);