<h4>Trocar senha para <?php echo $this->zfcUserDisplayName() ?></h4>
<?php if ($status === true) : ?>
    <div class="alert alert-success">Senha alterada com sucesso.</div>
<?php elseif ($status === false) : ?>
    <div class="alert alert-error">Não foi possível alterar sua senha. Por favor, tente novamente.</div>
<?php endif; ?>
<?php
$form = $this->changePasswordForm;

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changepassword'));
$form->setAttribute('method', 'post');

$emailElement = $form->get('identity');
$emailElement->setValue($this->zfcUserIdentity()->getEmail());

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?php echo $this->formElementErrors($form->get('identity')); ?>
    <?php echo $this->formInput($form->get('identity')); ?>
    <div class="row">
        <div class="col-md-2">
            <label for="credential">Senha atual</label>
            <?php echo $this->formInput($form->get('credential')) . $this->formElementErrors($form->get('credential')); ?></dd>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <label for="newCredential">Nova Senha</label>
            <?php echo $this->formInput($form->get('newCredential')) . $this->formElementErrors($form->get('newCredential')); ?></dd>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <label for="newCredentialVerify">Confirma Senha</label>
            <?php echo $this->formInput($form->get('newCredentialVerify')) . $this->formElementErrors($form->get('newCredentialVerify')); ?>
        </div>
    </div>
    <div>
        <?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-default')); ?>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
