<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
?>
<div class="account-container">
    <div class="content clearfix">
        <div class="brand"></div>
        <?php echo $this->form()->openTag($form) ?>
        <fieldset>
            <legend></legend>
            <div class="login-fields">
                <p>Faça login usando seu usuário e senha:</p>
                <?php echo $this->formElementErrors($form->get('identity')) ?>
                <div class="form-group field">
                    <?php echo $this->formLabel($form->get('identity')) ?>
                    <?php echo $this->formInput($form->get('identity')->setAttributes(array('class' => 'form-control login username-field', 'placeholder' => 'Usuário'))) ?>
                </div>
                <div class="field">
                    <?php echo $this->formLabel($form->get('credential')) ?>
                    <?php echo $this->formInput($form->get('credential')->setAttributes(array('class' => 'form-control login password-field', 'placeholder' => 'Senha'))) ?>
                </div>
                <?php if ($this->redirect): ?>
                    <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
                <?php endif ?>
                <?php echo $this->formButton($form->get('submit')->setLabel('Entrar')->setAttribute('class', 'button btn btn-danger')) ?>
            </div>
        </fieldset>
        <?php echo $this->form()->closeTag(); ?>
    </div>
    <div class="account-footer">
        <b>Seu IP: </b><?php echo $_SERVER['REMOTE_ADDR'] ?> |
        <b>Data: </b><?php echo date('d/m/Y') ?> | 
        <b>Hora: </b><?php echo date('H:i') ?>
    </div>
</div>