<?php
$title = $this->translate('Contas a Receber');
$this->headTitle($title);
?>
<div class="row">
    <div class="col-md-6">
        <h2 class="container-header">
            <i class="glyphicon glyphicon-arrow-up"></i> 
            <?php echo $this->escapeHtml($title); ?>
        </h2>
    </div>
    <div class="col-md-6">
        <div class="btn-group btn-group-sm pull-right">
            <a class="btn btn-default" href="<?php echo $this->url('admin/financial/payable/add', array('action' => 'add'));
            ?>"> 
                <i class="glyphicon glyphicon-plus"></i> 
                <?php echo $this->translate('Nova Conta'); ?>
            </a>
        </div>
    </div> 
</div>
<div class="row">
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title"><i class="glyphicon glyphicon-usd"></i> Total a Receber</h4>
            </div>
            <div class="panel-body" dir="rtl">
                <h4 class="text-success"><?php echo $this->currency($this->total['total']); ?></h4>
            </div>
        </div>
    </div>

    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title"><i class="glyphicon glyphicon-arrow-up"></i> Contas a Receber</h4>
            </div>
            <table class="table table-condensed table-hover">
                <tr>
                    <th class=""><?php echo $this->translate('DESCRIÇÃO'); ?></th>
                    <th class=""><?php echo $this->translate('RECEBER DE'); ?></th>
                    <th class=""><?php echo $this->translate('VALOR'); ?></th>
                    <th class="" colspan="2"><?php echo $this->translate('VENCIMENTO'); ?></th>
                </tr>
                <?php if (0 == count($this->payable)): ?>
                    <tr>
                        <td colspan="10" class="alert alert-info text-center"><?php echo $this->translate('Não há registros no banco de dados.') ?></td>
                    </tr>
                <?php else: ?>
                    <?php foreach ($this->payable as $payable) : ?>
                        <tr>
                            <td><?php echo $this->escapeHtml($payable->getAccount()->getAccountDescription()); ?></td>
                            <td><?php echo $this->escapeHtml($payable->getSupplierId()->getPerson()->getPersonName()); ?></td>
                            <td><?php echo $this->currency($payable->getAccount()->getAccountValue()); ?></td>
                            <td><?php echo $this->escapeHtml($payable->getAccount()->getAccountExpirationDate()); ?></td>
                            <td>
                                <div class="btn-group btn-group-xs pull-right">
                                    <a class="btn btn-default" data-toggle="modal" href="#dischargeModal"><i class="glyphicon glyphicon-download"></i></a>
                                    <a class="btn btn-default" href="<?php
                                    echo $this->url('admin/financial/payable/view', array('action' => 'view',
                                        'id' => $payable->getPayableId()));
                                    ?>"><i class="glyphicon glyphicon-folder-open"></i></a>
                                    <a class="btn btn-default" href="<?php echo $this->url('admin/financial/payable/edit', array('action' => 'edit', 'id' => $payable->getPayableId()))
                                    ?>"><i class="glyphicon glyphicon-edit"></i></a>
                                    <a class="btn btn-default" href="<?php echo $this->url('admin/financial/payable/delete', array('action' => 'delete', 'id' => $payable->getPayableId()))
                                    ?>"><i class="glyphicon glyphicon-remove"></i></a>
                                </div>
                            </td>
                        </tr>
                        <?php echo $this->partial('financial/account/discharge', array('account' => $payable, 'form' => $this->form)); ?>
                    <?php endforeach; ?>
                <?php endif; ?>
                </tbody>
            </table>
            <div class="panel-footer">
                <?php
                $paginationInfo = $this->placeholder('pagination');
                if (!isset($paginationInfo->route)) {
                    $paginationInfo->route = 'admin/financial/payable';
                    $paginationInfo->params = array();
                }
                ?>
                <?php echo $this->paginationControl($this->payable, 'Sliding', 'layout/pagination'); ?>
            </div>
        </div>
    </div>
</div>