<?php
$payable   = $this->payable;
$account     = $payable->getAccount();
$title = 'Detalhes da Conta a Pagar';
$this->headTitle($title);
?>
<div class="">
        <legend>
            <h1>Conta a Pagar</h1>
            <div class="row">
                <div class="col-md-6">
                    <small><strong>Receber de: </strong><?php echo $payable->getSupplierId()->getSupplierName(); ?></small>
                </div>
                <div class="col-md-6">
                    <div class="btn-group btn-group-sm pull-right">
                        <a class="btn btn-default" href="<?php echo $this->url('admin/financial/payable/add', array('action' => 'add'));?>"><i class="glyphicon glyphicon-plus"></i> Novo</a></li>
                        <a class="btn btn-default" href="<?php echo $this->url('admin/financial/payable/add', array('action' => 'add'));?>"><i class="glyphicon glyphicon-plus"></i> Novo</a></li>
                        <a class="btn btn-default" href="<?php echo $this->url('admin/financial/payable/edit', array('action' => 'edit',
                            'id' => $payable->getPayableId()));?>"><i class="glyphicon glyphicon-edit"></i> <?php echo $this->translate('Editar');?></a>
                        <a class="btn btn-default" href="<?php echo $this->url('admin/financial/payable/delete', array('action' => 'delete',
                            'id' => $payable->getPayableId()));?>"><i class="glyphicon glyphicon-remove"></i> <?php echo $this->translate('Apagar');?></a>
                        <a class="btn btn-default" href="<?php echo $this->url('admin/financial/payable');?>"><i class="glyphicon glyphicon-chevron-left"></i> <?php echo $this->translate('Voltar');?></a>
                    </div>
                </div>
            </div>
        </legend>
    <dl class="dl-horizontal">
        <div class="row">
            <div class="col-md-6">
                <dt>Cód.:</dt>
                <dd><?php echo $payable->getPayableId(); ?>&nbsp;</dd>
                <dt>Cliente:</dt>
                <dd><?php echo $payable->getSupplierId()->getSupplierName(); ?>&nbsp;</dd>
                <dt>Referente a:</dt>
                <dd><?php echo $account->getAccountDescription(); ?>&nbsp;</dd>
                <dt>Portador:</dt>
                <dd><?php echo $account->getAccountCarrier(); ?>&nbsp;</dd>
                <dt>Código de Barras:</dt>
                <dd><?php echo $account->getAccountBarcode(); ?>&nbsp;</dd>
                <dt>Lançamento Automático:</dt>
                <dd><?php echo ($account->getAccountBarcode()) ? "Sim": "Não"; ?>&nbsp;</dd>
                <dt>Conta:</dt>
                <dd><?php echo $account->getCurrentAccountId()->getCurrentAccountName(); ?>&nbsp;</dd>
                <dt>Forma de Pagamento:</dt>
                <dd><?php echo $account->getPaymentTypeId()->getPaymentTypeName(); ?>&nbsp;</dd>
                <dt>Ítem Contábil:</dt>
                <dd><?php echo $account->getAccountingItemId()->getAccountingItemName(); ?>&nbsp;</dd>
                <dt>Centro de Custos:</dt>
                <dd><?php echo $account->getDepartmentId()->getDepartmentName(); ?>&nbsp;</dd>
                <dt>Tipo de Documento:</dt>
                <dd><?php echo $account->getDocumentTypeId()->getDocumentTypeName(); ?>&nbsp;</dd>
            </div>
            <div class="col-md-6">
                <dt>Auto Cód.:</dt>
                <dd><?php echo $account->getAccountAutoId(); ?>&nbsp;</dd>
                <dt>Data de Emissão:</dt>
                <dd><?php echo $account->getAccountEmissionDate(); ?>&nbsp;</dd>
                <dt>Data de Vencimento:</dt>
                <dd><?php echo $account->getAccountExpirationDate(); ?>&nbsp;</dd>
                <dt>Valor:</dt>
                <dd><?php echo $this->currency($account->getAccountValue()); ?>&nbsp;</dd>
                <dt>Multa:</dt>
                <dd><?php echo $this->porcent($account->getAccountFine()); ?>&nbsp;</dd>
                <dt>Juros:</dt>
                <dd><?php echo $this->porcent($account->getAccountInterest()); ?>&nbsp;</dd>
                <dt>Parcelas:</dt>
                <dd><?php echo (int) $account->getAccountParcels(); ?> parcela(s).</dd>
            </div>
        </div>
    </dl>
</div>