<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Dartalla ' . $this->translate('Solução em serviços na internet'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/font-awesome/css/font-awesome.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>
        <!--[if lt IE 9]>
                <script src="assets/js/html5shiv.js"></script>
                <script src="assets/js/respond.min.js"></script>
        <![endif]-->
    </head>
    <body data-spy="scroll" data-target=".navbar" data-offset="100">
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                        <img src="/img/logo.png" alt="logo">
                        &nbsp;<?php echo $this->translate('Dartalla') ?>
                    </a>
                </div>
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="#"><?php echo $this->translate('Home') ?></a></li>
                        <li><a href="#about">A Empresa</a></li>
                        <li><a href="#pricing">Produtos e Serviços</a></li>
                        <li><a href="#">Preços e Planos</a></li>
                        <li><a href="#">Portifólio</a></li>
                        <li><a href="#">Contato</a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <section class="wrapper-sm bg-primary">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <i class="icon icon-user"></i> Olá, Convidado. <a class="btn btn-login" href="#">Login aqui &raquo;</a>
                    </div>
                </div>
            </div>
        </section>
        
            <?php echo $this->content; ?>
        
        <footer class="wrapper-sm bg-secondary">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <p>Desenvolvido por <a href="http://dartalla.com" target="_blank">Dartalla &copy;.</a></p>
                    </div>
                </div>
            </div>
        </footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
