<?php
$sale = $this->sale;
$saleDetails = $sale->getSaleDetails();
$order = $sale->getOrder();
$title = 'Detalhes da Venda - nº ' . $sale->getSaleId();
$this->headTitle($title);
?>
<div class="container-fluid">
    <legend>
        <h1>Dados da Venda</h1>
        <div class="row-fluid">
            <div class="span6">
                <small><strong>Cliente: </strong><?php echo $order->getCustomerId()->getCustomerName(); ?></small>
            </div>
            <div class="pull-right">
                <div class="btn-group">
                    <a class="btn" href="<?php echo $this->url('admin/business/sale/add', array('action' => 'add')); ?>"><i class="icon-plus"></i> Novo</a></li>
                    <a class="btn" href="<?php
echo $this->url('admin/business/sale/delete', array('action' => 'delete',
    'id' => $sale->getSaleId()));
?>"><i class="icon-remove"></i> <?php echo $this->translate('Apagar'); ?></a>
                    <a class="btn" href="<?php echo $this->url('admin/business/sale'); ?>"><i class="manager-icon-unshare"></i> <?php echo $this->translate('Voltar'); ?></a>
                </div>
            </div>
        </div>
    </legend>
    <dl class="dl-horizontal">
        <div class="row-fluid">
            <div class="span5">
                <dt>Cód.:</dt>
                <dd><?php echo $sale->getSaleId(); ?>&nbsp;</dd>
                <dt>Cliente.:</dt>
                <dd><?php echo $order->getCustomerId()->getCustomerName(); ?>&nbsp;</dd>
                <dt>Operador.:</dt>
                <dd><?php echo $order->getEmployeeId()->getEmployeeName(); ?>&nbsp;</dd>
            </div>
            <div class="span6">
                <dt>Cód. Automático:</dt>
                <dd><?php echo $order->getOrderUId(); ?>&nbsp;</dd>
                <dt>Data:</dt>
                <dd><?php echo $order->getOrderDate(); ?>&nbsp;</dd>
            </div>
        </div>
        <br>
        <table class="table">
            <thead>
                <tr>
                    <th class="span1"><?php echo $this->translate('Cód.'); ?></th>
                    <th><?php echo $this->translate('Descrição'); ?></th>
                    <th class="span1"><?php echo $this->translate('Qtde'); ?></th>
                    <th class="span2"><?php echo $this->translate('Preço Unit.'); ?></th>
                    <th class="span2"><?php echo $this->translate('Subtotal'); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php if (count($saleDetails)): ?>
                    <?php $items = 0; ?>
                    <?php foreach ($saleDetails as $detail): ?>
                        <tr>
                            <td><?php echo $detail->getProductId()->getProductId(); ?></td>
                            <td><?php echo $detail->getProductId()->getProductName(); ?></td>
                            <td><?php echo $detail->getSaleDetailQuantity(); ?></td>
                            <td><?php echo $this->currency($detail->getProductId()->getProductPrice()); ?></td>
                            <td><?php echo $this->currency($detail->getSaleDetailTotal()); ?></td>
                            <?php $items += $detail->getSaleDetailQuantity(); ?>
                        </tr>
                    <?php endforeach; ?>
                <?php else: ?>
                    <?php echo $this->info('Nenhum produto foi incluído nessa venda.'); ?>
                <?php endif; ?>
                <tr class="info">
                    <td>&nbsp;</td>
                    <td class="lead" style="text-align: right;">Total:</td>
                    <td class="lead"><?php echo (int) $items; ?></td>
                    <td>&nbsp;</td>
                    <td class="lead"><?php echo $this->currency($order->getOrderTotal()); ?></td>
                </tr>
            </tbody>
        </table>
    </dl>
</div>
