<?php $address = $this->address ?>
<?php echo $this->formHidden($address->get('addressId')); ?>
<div class="row">
    <div class="col-md-4">
        <?php echo $this->formLabel($address->get('addressName')); ?>
        <?php echo $this->formText($address->get('addressName')); ?>
    </div>
    <div class="col-md-2">
        <?php echo $this->formLabel($address->get('addressNumber')); ?>
        <?php echo $this->formText($address->get('addressNumber')); ?>
    </div>
</div>
<div class="row">
    <div class="col-md-2">
        <?php echo $this->formLabel($address->get('addressComplement')); ?>
        <?php echo $this->formText($address->get('addressComplement')); ?>
    </div>
    <div class="col-md-2">
        <?php echo $this->formLabel($address->get('addressQuarter')); ?>
        <?php echo $this->formText($address->get('addressQuarter')); ?>
    </div>
    <div class="col-md-2">
        <?php echo $this->formLabel($address->get('addressPostalCode')); ?>
        <?php echo $this->formText($address->get('addressPostalCode')); ?>
    </div>
</div>
<div class="row">
    <div class="col-md-2">
        <?php echo $this->formLabel($address->get('addressCity')); ?>
        <?php echo $this->formText($address->get('addressCity')); ?>
    </div>
    <div class="col-md-2">
        <?php echo $this->formLabel($address->get('addressState')); ?>
        <?php echo $this->formText($address->get('addressState')); ?>
    </div>
    <div class="col-md-1">
        <?php echo $this->formLabel($address->get('addressCountry')); ?>
        <?php echo $this->formText($address->get('addressCountry')); ?>
    </div>
</div>