<?php
$customer = $this->customer;
$person = $customer->getPerson();
$address = $person->getAddress();
$contact = $person->getContact();
$individual = $person->getIndividual();
$legal = $person->getLegal();
$title = 'Detalhes de ' . $person->getPersonName();
$this->headTitle($title);
?>
<div class="row">
    <div class="col-md-8">
        <blockquote>
            <p class="text-danger"><?php echo $person->getPersonName(); ?></small>
        </blockquote>
    </div>
    <div class="col-md-4">
        <div class="btn-group pull-right">
            <div class="btn-group">
                <a class="btn btn-default dropdown-toggle" data-toggle="dropdown" href="#"> <i class="glyphicon glyphicon-plus"></i> <?php echo $this->translate('Novo'); ?> &nbsp; <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="<?php
                        echo $this->url('admin/customer/add', array('action' => 'add',
                            'type' => base64_encode(0)));
                        ?>"><i class="glyphicon glyphicon-user"></i> Pessoa Física</a></li>
                    <li><a href="<?php
                        echo $this->url('admin/customer/add', array('action' => 'add',
                            'type' => base64_encode(1)));
                        ?>"><i class="fa fa-legal"></i> Pessoa Jurídica</a></li>
                </ul>
            </div>
            <a class="btn btn-default" href="<?php
            echo $this->url('admin/customer/edit', array('action' => 'edit',
                'id' => $customer->getCustomerId(), 'type' => base64_encode($customer->getPerson()->getPersonType())));
            ?>"><i class="glyphicon glyphicon-edit"></i> <?php echo $this->translate('Editar'); ?></a>
            <a class="btn btn-default" href="<?php
            echo $this->url('admin/customer/delete', array('action' => 'delete',
                'id' => $customer->getCustomerId()));
            ?>"><i class="glyphicon glyphicon-remove"></i> <?php echo $this->translate('Apagar'); ?></a>
            <a class="btn btn-default" href="<?php echo $this->url('admin/customer'); ?>"><i class="glyphicon glyphicon-chevron-left"></i> <?php echo $this->translate('Voltar'); ?></a>
        </div>
    </div>
</div>
<dl class="dl-horizontal">
    <?php if ($person->getPersonType()): ?>
        <legend>Dados da Pessoa Jurídica</legend>
        <dt>CNPJ:</dt>
        <dd><?php echo $this->cnpj($legal->getLegalCnpj()); ?>&nbsp;</dd>
        <dt>Inscrição Estadual:</dt>
        <dd><?php echo $legal->getLegalSubscription(); ?>&nbsp;</dd>
        <dt>Representante:</dt>
        <dd><?php echo $legal->getLegalRepresentativeName(); ?>&nbsp;</dd>
        <dt>Telefone do Rep.:</dt>
        <dd><?php echo $this->phone($legal->getLegalRepresentativePhone()); ?>&nbsp;</dd>
    <?php else: ?>
        <legend>Dados da Pessoa Física</legend>
        <div class="row">
            <div class="col-md-6">
                <dt>CPF:</dt>
                <dd><?php echo $this->cpf($individual->getIndividualCpf()); ?>&nbsp;</dd>
                <dt>RG:</dt>
                <dd><?php echo $individual->getIndividualRg(); ?>&nbsp;</dd>
                <dt>Sexo:</dt>
                <dd><?php echo $this->gender($individual->getIndividualGender()); ?>&nbsp;</dd>
                <dt>Natural de:</dt>
                <dd><?php echo $individual->getIndividualBirthPlace(); ?>/<?php echo $individual->getIndividualBirthUf(); ?>&nbsp;</dd>
                <dt>Nome da Mãe:</dt>
                <dd><?php echo $individual->getIndividualMother(); ?>&nbsp;</dd>
            </div>
            <div class="col-md-6">
                <dt>Data de Nascimento:</dt>
                <dd><?php echo $this->birthday($individual->getIndividualBirthDay(), $individual->getIndividualBirthMonth(), $individual->getIndividualBirthYear()); ?></dd>
                <dt>Órgão Expedidor:</dt>
                <dd><?php echo $individual->getIndividualRgOrgan(); ?> / <?php echo $individual->getIndividualRgUf(); ?></dd>
                <dt>Data de Expedição:</dt>
                <dd><?php echo $this->date($individual->getIndividualRgDate()); ?>&nbsp;</dd>
                <dt>Nacionalidade:</dt>
                <dd><?php echo $individual->getIndividualNationality(); ?>&nbsp;</dd>
                <dt>Nome do Pai:</dt>
                <dd><?php echo $individual->getIndividualFather(); ?>&nbsp;</dd>
            </div>
        </div>
    <?php endif; ?>

    <legend>Dados de Contato</legend>
    <div class="row">
        <div class="col-md-6">
            <dt>Endereço:</dt>
            <dd><?php echo $address->getAddressName(); ?>, nº <?php echo $address->getAddressNumber(); ?></dd>
            <dt>Complemento:</dt>
            <dd><?php echo $address->getAddressComplement(); ?>&nbsp;</dd>
            <dt>Bairro:</dt>
            <dd><?php echo $address->getAddressQuarter(); ?>&nbsp;</dd>
            <dt>CEP:</dt>
            <dd><?php echo $this->cep($address->getAddressPostalCode()); ?>&nbsp;</dd>
            <dt>Cidade:</dt>
            <dd><?php echo $address->getAddressCity(); ?>&nbsp;</dd>
            <dt>Estado:</dt>
            <dd><?php echo $address->getAddressState(); ?>&nbsp;</dd>
            <dt>País:</dt>
            <dd><?php echo $address->getAddressCountry(); ?>&nbsp;</dd>
        </div>
        <div class="col-md-6">
            <dt>Email:</dt>
            <dd><?php echo $contact->getContactEmail(); ?>&nbsp;</dd>
            <dt>Website:</dt>
            <dd><?php echo $contact->getContactWebsite(); ?>&nbsp;</dd>
            <dt>Telefone:</dt>
            <dd><?php echo $this->phone($contact->getContactPhone()); ?>&nbsp;</dd>
            <dt>Celular:</dt>
            <dd><?php echo $this->phone($contact->getContactCell()); ?>&nbsp;</dd>
            <dt>FAX:</dt>
            <dd><?php echo $this->phone($contact->getContactFax()); ?>&nbsp;</dd>
        </div>
    </div>

    <?php if (!$customer->getPerson()->getPersonType()  && ($customer->getPerson()->getIndividual()->getProfessional())): ?>
        <legend>Dados Profissionais</legend>
        <div class="row">
            <div class="col-md-6">
                <dt>Nome da Empresa:</dt>
                <dd><?php echo $customer->getPerson()->getIndividual()->getProfessional()->getProfessionalEnterpriseName(); ?></dd>
                <dt>Ramo de Atividade:</dt>
                <dd><?php echo $customer->getPerson()->getIndividual()->getProfessional()->getProfessionalEnterpriseBusiness(); ?></dd>
                <dt>Endereço:</dt>
                <dd><?php echo $customer->getPerson()->getIndividual()->getProfessional()->getAddress()->getAddressName(); ?>, nº <?php echo $customer->getPerson()->getAddress()->getAddressNumber(); ?></dd>
                <dt>Complemento:</dt>
                <dd><?php echo $customer->getPerson()->getIndividual()->getProfessional()->getAddress()->getAddressComplement(); ?>&nbsp;</dd>
                <dt>Bairro:</dt>
                <dd><?php echo $customer->getPerson()->getIndividual()->getProfessional()->getAddress()->getAddressQuarter(); ?>&nbsp;</dd>
                <dt>CEP:</dt>
                <dd><?php echo $this->cep($customer->getPerson()->getIndividual()->getProfessional()->getAddress()->getAddressPostalCode()); ?>&nbsp;</dd>
                <dt>Cidade:</dt>
                <dd><?php echo $customer->getPerson()->getIndividual()->getProfessional()->getAddress()->getAddressCity(); ?>&nbsp;</dd>
                <dt>Estado:</dt>
                <dd><?php echo $customer->getPerson()->getIndividual()->getProfessional()->getAddress()->getAddressState(); ?>&nbsp;</dd>
                <dt>País:</dt>
                <dd><?php echo $customer->getPerson()->getIndividual()->getProfessional()->getAddress()->getAddressCountry(); ?>&nbsp;</dd>
                <dt>Data de Admissão:</dt>
                <dd><?php echo $customer->getPerson()->getIndividual()->getProfessional()->getProfessionalAdmissionDate(); ?></dd>
                <dt>Cargo:</dt>
                <dd><?php echo $customer->getPerson()->getIndividual()->getProfessional()->getProfessionalOffice(); ?></dd>
                <dt>Salário:</dt>
                <dd><?php echo $this->currency($customer->getPerson()->getIndividual()->getProfessional()->getProfessionalSalary()); ?></dd>
            </div>
            <div class="col-md-6">
                <dt>CNPJ:</dt>
                <dd><?php echo $this->cnpj($customer->getPerson()->getIndividual()->getProfessional()->getProfessionalEnterpriseCnpj()); ?>&nbsp;</dd>
                <dt>Data de Fundação:</dt>
                <dd><?php echo $this->date($customer->getPerson()->getIndividual()->getProfessional()->getProfessionalEnterpriseFoundationDate()); ?>&nbsp;</dd>
                <dt>Email:</dt>
                <dd><?php echo $customer->getPerson()->getIndividual()->getProfessional()->getContact()->getContactEmail(); ?>&nbsp;</dd>
                <dt>Website:</dt>
                <dd><?php echo $customer->getPerson()->getIndividual()->getProfessional()->getContact()->getContactWebsite(); ?>&nbsp;</dd>
                <dt>Telefone:</dt>
                <dd><?php echo $this->phone($customer->getPerson()->getIndividual()->getProfessional()->getContact()->getContactPhone()); ?>&nbsp;</dd>
                <dt>Celular:</dt>
                <dd><?php echo $this->phone($customer->getPerson()->getIndividual()->getProfessional()->getContact()->getContactCell()); ?>&nbsp;</dd>
                <dt>FAX:</dt>
                <dd><?php echo $this->phone($customer->getPerson()->getIndividual()->getProfessional()->getContact()->getContactFax()); ?>&nbsp;</dd>
                <dt>Particição nos Lucros:</dt>
                <dd><?php echo $this->porcent($customer->getPerson()->getIndividual()->getProfessional()->getProfessionalEnterpriseParticipation()); ?>&nbsp;</dd>
                <dt>Nº de Sócios:</dt>
                <dd><?php echo $customer->getPerson()->getIndividual()->getProfessional()->getProfessionalEnterprisePartnerCount(); ?>&nbsp;</dd>
                <dt>Nº do Benefício:</dt>
                <dd><?php echo $customer->getPerson()->getIndividual()->getProfessional()->getProfessionalBenefitNumber(); ?>&nbsp;</dd>
                <dt>Outra Renda:</dt>
                <dd><?php echo $this->currency($customer->getPerson()->getIndividual()->getProfessional()->getProfessionalOtherRevenue()); ?>&nbsp;</dd>
                <dt>Tipo de Residência:</dt>
                <dd><?php echo $customer->getCustomerResidenceType(); ?></dd>
                <dt>Tempo na Residência:</dt>
                <dd><?php echo $customer->getCustomerResidenceTime(); ?></dd>
                <dt>Observações:</dt>
                <dd><?php echo $customer->getPerson()->getIndividual()->getProfessional()->getProfessionalNotes(); ?>&nbsp;</dd>
            </div>
        </div>
    <?php endif; ?>
    <br/>
    <?php if (($customer->getPerson()->getPersonType() == 0) && (count($customer->getPerson()->getIndividual()->getProfessionalAddon()))): ?>
        <legend>Dados Adicionais</legend>
        <div class="row">
            <div class="col-md-6">
                <dt>Empresa Anterior:</dt>
                <dd><?php echo $customer->getPerson()->getIndividual()->getProfessionalAddon()->getProfessionalAddonPreviousCompany(); ?></dd>
                <dt>Data de Admissão:</dt>
                <dd><?php echo $customer->getPerson()->getIndividual()->getProfessionalAddon()->getProfessionalAddonPreviousAdmission(); ?></dd>
                <dt>Cargo Anterior:</dt>
                <dd><?php echo $customer->getPerson()->getIndividual()->getProfessionalAddon()->getProfessionalAddonPreviousOffice(); ?></dd>
            </div>
            <div class="col-md-6">
                <dt>Telefone:</dt>
                <dd><?php echo $this->phone($customer->getPerson()->getIndividual()->getProfessionalAddon()->getProfessionalAddonPreviousPhone()); ?>&nbsp;</dd>
                <dt>Data de Demissão:</dt>
                <dd><?php echo $customer->getPerson()->getIndividual()->getProfessionalAddon()->getProfessionalAddonPreviousDemission(); ?></dd>
                <dt>Salário Anterior:</dt>
                <dd><?php echo $this->currency($customer->getPerson()->getIndividual()->getProfessionalAddon()->getProfessionalAddonPreviousSalary()); ?></dd>
            </div>
        </div>
    <?php endif; ?>
    <br/>
    <?php if (count($customer->getCustomerBankAccount()) > 0): ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-title"><i class="glyphicon glyphicon-usd"></i> Contas Bancárias do Cliente</div>
            </div>
            <table class="table table-condensed table-hover">
                <tr>
                    <th class=""><?php echo $this->translate('TIPO DA CONTA'); ?></th>
                    <th class=""><?php echo $this->translate('BANCO'); ?></th>
                    <th class=""><?php echo $this->translate('AGÊNCIA'); ?></th>
                    <th class=""><?php echo $this->translate('CONTA'); ?></th>
                    <th class=""><?php echo $this->translate('CLIENTE DESDE'); ?></th>
                </tr>
                <?php foreach ($customer->getCustomerBankAccount() as $customerBankAccount) : ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($customerBankAccount->getBankAccountType()); ?></td>
                        <td><?php echo $this->escapeHtml($customerBankAccount->getBankAccountBank()); ?></td>
                        <td><?php echo $this->escapeHtml($customerBankAccount->getBankAccountAgency()); ?></td>
                        <td><?php echo $this->escapeHtml($customerBankAccount->getBankAccountAccount()); ?></td>
                        <td><?php echo $this->escapeHtml($customerBankAccount->getBankAccountSince()); ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    <?php endif; ?>
    <br/>
    <?php if (count($customer->getCustomerPatrimony()) > 0): ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1 class="panel-title"><i class="fa fa-building"></i> Patrimônio do Cliente</h1>
            </div>
            <table class="table table-condensed table-hover">
                <tr>
                    <th class=""><?php echo $this->translate('PATRIMÔNIO'); ?></th>
                    <th class=""><?php echo $this->translate('VALOR'); ?></th>
                </tr>
                <?php foreach ($customer->getCustomerPatrimony() as $customerPatrimony) : ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($customerPatrimony->getPatrimonyName()); ?></td>
                        <td><?php echo $this->currency($customerPatrimony->getPatrimonyValue()); ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    <?php endif; ?>
    <br/>
    <?php if (count($customer->getCustomerReference()) > 0): ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1 class="panel-title"><i class="glyphicon glyphicon-thumbs-up"></i> Referências do Cliente</h1>
            </div>
            <table class="table table-condensed table-hover">
                <tr>
                    <th class=""><?php echo $this->translate('TIPO'); ?></th>
                    <th class=""><?php echo $this->translate('REFERÊNCIA'); ?></th>
                    <th class=""><?php echo $this->translate('TELEFONE'); ?></th>
                </tr>
                <?php foreach ($customer->getCustomerReference() as $customerReference) : ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($customerReference->getReferenceType()); ?></td>
                        <td><?php echo $this->escapeHtml($customerReference->getReferenceName()); ?></td>
                        <td><?php echo $this->phone($customerReference->getReferencePhone()); ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    <?php endif; ?>
</dl>