<?php
$title = $this->translate('Delete Employee');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><?php echo $this->translate('Are you sure that you want to delete')?>
    '<?php echo $this->escapeHtml($this->employee->getPerson()->getPersonName()); ?>'?
</p>
<?php
$url = $this->url('admin/employee/delete', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $this->employee->getEmployeeId(); ?>" />
    <input type="submit" name="del" value="Sim" class="btn btn-default" />
    <input type="submit" name="del" value="Não" class="btn btn-default" />
</div>
</form>
