<?php
$title = $this->translate('Funcionários');
$this->headTitle($title);
?>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-8">
                <div class="panel-title"><i class="glyphicon glyphicon-wrench"></i> <?php echo $this->escapeHtml($title); ?> </div>
            </div>
            <div class="col-md-4">
                <div class="btn-group btn-group-sm pull-right">
                    <a class="btn btn-default" href="<?php echo $this->url('admin/employee/add', array('action' => 'add')); ?>"> <i class="glyphicon glyphicon-plus"></i> <?php echo $this->translate('Novo'); ?></a>
                </div>
            </div> 
        </div>
    </div>
    <table class="table table-condensed table-hover">
        <thead>
            <tr>
                <th class=""><?php echo $this->translate('CÓD'); ?></th>
                <th class=""><?php echo $this->translate('FUNCIONÁRIO'); ?></th>
                <th class=""><?php echo $this->translate('CARGO'); ?></th>
                <th class=""><?php echo $this->translate('TELEFONE'); ?></th>
                <th class=""><?php echo $this->translate('SITUAÇÃO'); ?></th>
                <th class="col-md-2"></th>
            </tr>
        </thead>
        <tbody>
            <?php if (0 == count($this->employee)): ?>
                <tr>
                    <td colspan="10" class="alert alert-info text-center"><?php echo $this->translate('Não há nenhum dado no banco de dados.') ?></td>
                </tr>
            <?php else: ?>
                <?php foreach ($this->employee as $employee): ?>
                    <tr>
                        <td><?php echo str_pad($employee->getEmployeeId(), 8,'0',STR_PAD_LEFT); ?></td>
                        <td><?php echo $this->escapeHtml($employee->getPerson()->getPersonName()); ?></td>
                        <td><?php echo $this->escapeHtml($employee->getOfficeId()->getOfficeName()); ?></td>
                        <td><?php echo $this->phone($employee->getPerson()->getContact()->getContactPhone()); ?></td>
                        <td><?php echo $this->escapeHtml($employee->getEmployeeStatusId()->getEmployeeStatusName()); ?></td>
                        <td>
                            <div class="btn-group btn-group-xs pull-right">
                                <a class="btn btn-default btn-mini" href="<?php
                                echo $this->url('admin/employee/view', array('action' => 'view',
                                    'id' => $employee->getEmployeeId()));
                                ?>"><i class="glyphicon glyphicon-folder-open"></i></a>
                                <a class="btn btn-default btn-mini" href="<?php
                                echo $this->url('admin/employee/edit', array('action' => 'edit',
                                    'id' => $employee->getEmployeeId()));
                                ?>"><i class="glyphicon glyphicon-edit"></i></a>
                                <a class="btn btn-default btn-mini" href="<?php
                                echo $this->url('admin/employee/delete', array('action' => 'delete',
                                    'id' => $employee->getEmployeeId()));
                                ?>"><i class="glyphicon glyphicon-remove"></i></a>
                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php endif; ?>
        </tbody>
    </table>
    <div class="panel-footer">
        <?php
        $paginationInfo = $this->placeholder('pagination');
        if (!isset($paginationInfo->route)) {
            $paginationInfo->route = 'admin/employee';
            $paginationInfo->params = array();
        }
        ?>
        <?php echo $this->paginationControl($this->employee, 'Sliding', 'layout/pagination'); ?>
    </div>
</div>