<?php
$employee   = $this->employee;
$person     = $employee->getPerson();
$address    = $person->getAddress();
$contact    = $person->getContact();
$individual = $person->getIndividual();
$title = 'Detalhes de ' . $person->getPersonName();
$this->headTitle($title);
?>
<div class="row">
    <div class="col-md-6">
        <blockquote>
            <p class="text-danger"><?php echo $person->getPersonName(); ?></p>
        </blockquote>
    </div>
    <div class="col-md-6">
        <div class="btn-group pull-right">
            <a class="btn btn-default" href="<?php echo $this->url('admin/employee/add', array('action' => 'add')); ?>"> <i class="glyphicon glyphicon-plus"></i> <?php echo $this->translate('Novo'); ?></a>
            <a class="btn btn-default" href="<?php echo $this->url('admin/employee/edit', array('action' => 'edit', 'id' => $employee->getEmployeeId()));?>"><i class="glyphicon glyphicon-edit"></i> <?php echo $this->translate('Editar');?></a>
            <a class="btn btn-default" href="<?php echo $this->url('admin/employee/delete', array('action' => 'delete', 'id' => $employee->getEmployeeId()));?>"><i class="glyphicon glyphicon-remove"></i> <?php echo $this->translate('Apagar');?></a>
            <a class="btn btn-default" href="<?php echo $this->url('admin/employee');?>"><i class="glyphicon glyphicon-chevron-left"></i> <?php echo $this->translate('Voltar');?></a>
        </div>
    </div>
</div>
<dl class="dl-horizontal">
    <legend>Dados da Pessoa Física</legend>
    <div class="row">
        <div class="col-md-5">
            <dt>CPF:</dt>
            <dd><?php echo $this->cpf($individual->getIndividualCpf()); ?>&nbsp;</dd>
            <dt>RG:</dt>
            <dd><?php echo $individual->getIndividualRg(); ?>&nbsp;</dd>
            <dt>Sexo:</dt>
            <dd><?php echo $this->gender($individual->getIndividualGender()); ?>&nbsp;</dd>
            <dt>Natural de:</dt>
            <dd><?php echo $individual->getIndividualBirthPlace(); ?>/<?php echo $individual->getIndividualBirthUf();?>&nbsp;</dd>
            <dt>Nome da Mãe:</dt>
            <dd><?php echo $individual->getIndividualMother(); ?>&nbsp;</dd>
        </div>
        <div class="col-md-5">
            <dt>Data de Nascimento:</dt>
            <dd>
                <?php echo $individual->getIndividualBirthDay();?>/<?php echo $individual->getIndividualBirthMonth();?>/<?php echo $individual->getIndividualBirthYear(); ?>
            </dd>
            <dt>Órgão Expedidor:</dt>
            <dd><?php echo $individual->getIndividualRgOrgan(); ?> / <?php echo $individual->getIndividualRgUf(); ?></dd>
            <dt>Data de Expedição:</dt>
            <dd><?php echo $this->date($individual->getIndividualRgDate()); ?>&nbsp;</dd>
            <dt>Nacionalidade:</dt>
            <dd><?php echo $individual->getIndividualNationality(); ?>&nbsp;</dd>
            <dt>Nome do Pai:</dt>
            <dd><?php echo $individual->getIndividualFather(); ?>&nbsp;</dd>
        </div>
    </div>

    <legend>Endereço</legend>
    <dt>Endereço:</dt>
    <dd><?php echo $address->getAddressName(); ?>, nº <?php echo $address->getAddressNumber(); ?></dd>
    <dt>Complemento:</dt>
    <dd><?php echo $address->getAddressComplement(); ?>&nbsp;</dd>
    <dt>Bairro:</dt>
    <dd><?php echo $address->getAddressQuarter(); ?>&nbsp;</dd>
    <dt>CEP:</dt>
    <dd><?php echo $this->cep($address->getAddressPostalCode()); ?>&nbsp;</dd>
    <dt>Cidade:</dt>
    <dd><?php echo $address->getAddressCity(); ?>&nbsp;</dd>
    <dt>Estado:</dt>
    <dd><?php echo $address->getAddressState(); ?>&nbsp;</dd>
    <dt>País:</dt>
    <dd><?php echo $address->getAddressCountry(); ?>&nbsp;</dd>

    <legend>Contato</legend>
    <dt>Email:</dt>
    <dd><?php echo $contact->getContactEmail(); ?>&nbsp;</dd>
    <dt>Website:</dt>
    <dd><?php echo $contact->getContactWebsite(); ?>&nbsp;</dd>
    <dt>Telefone:</dt>
    <dd><?php echo $this->phone($contact->getContactPhone()); ?>&nbsp;</dd>
    <dt>Celular:</dt>
    <dd><?php echo $this->phone($contact->getContactCell()); ?>&nbsp;</dd>
    <dt>FAX:</dt>
    <dd><?php echo $this->phone($contact->getContactFax()); ?>&nbsp;</dd>

    <legend>Dados do Funcionário</legend>
    <dt>Data de Admissão:</dt>
    <dd><?php echo $this->date($employee->getEmployeeAdmissionDate()); ?>&nbsp;</dd>
    <dt>Data de Demissão:</dt>
    <dd><?php echo $this->date($employee->getEmployeeDemissionDate()); ?>&nbsp;</dd>
    <dt>Carga Horária:</dt>
    <dd><?php echo $employee->getEmployeeWorkTime(); ?> hs</dd>
    <div class="row">
        <div class="col-md-2">
            <dt>CTPS:</dt>
            <dd><?php echo $employee->getEmployeeCtps(); ?>&nbsp;</dd>
        </div>
        <div class="col-md-1">
            <dt>Série:</dt>
            <dd><?php echo $employee->getEmployeeCtpsSerie(); ?>&nbsp;</dd>
        </div>
    </div>
    <dt>PIS:</dt>
    <dd><?php echo $employee->getEmployeePis(); ?>&nbsp;</dd>
    <dt>Salário:</dt>
    <dd><?php echo $employee->getEmployeeSalary(); ?>&nbsp;</dd>
    <dt>Bônus:</dt>
    <dd><?php echo $employee->getEmployeeBonus(); ?>&nbsp;</dd>
    <dt>Comissão:</dt>
    <dd><?php echo $employee->getEmployeeCommission(); ?>&nbsp;</dd>
</dl>