<?php
    $title = $this->translate('Unidade');
    $this->headTitle($title);
?>
<h1 class="row-fluid">
    <div class="span6">
        <?php echo $this->escapeHtml($title); ?>
    </div>
    <div class="pull-right">
        <div class="btn-group">
            <a class="btn" href="<?php echo $this->url('admin/unit/add', array('action'=>'add'));?>"> <i class="icon-plus"></i> <?php echo $this->translate('Novo'); ?></a>
        </div>
    </div> 
</h1>

<div class="widget widget-table">
    <div class="widget-header">
        <i class="manager-icon-gift"></i>
        <h3>Unidades</h3>
    </div>
    <div class="widget-content">
        <table class="table table-bordered">
            <tr>
                <th class="span1"><?php echo $this->translate('Sigla');?></th>
                <th class=""><?php echo $this->translate('Unidade');?></th>
                <th class="span1"><?php echo $this->translate('Ações');?></th>
            </tr>
            <?php if (0 == count($this->unit)):?>
            <tr>
                <td colspan="3"><?php echo $this->translate('Não há registros no banco de dados.')?></td>
            </tr>
            <?php else: ?>
            <?php foreach ($this->unit as $unit) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($unit->getUnitSymbol());?></td>
                <td><?php echo $this->escapeHtml($unit->getUnitName());?></td>
                <td>
                    <div class="btn-group">
                        <a class="btn btn-mini" href="<?php echo $this->url('admin/unit/edit',
                                array('action'=>'edit', 'id' => $unit->getUnitId()))?>"><i class="icon-edit"></i></a>
                        <a class="btn btn-mini" href="<?php echo $this->url('admin/unit/delete',
                            array('action'=>'delete', 'id' => $unit->getUnitId()))?>"><i class="icon-remove"></i></a>
                    </div>
                </td>
            </tr>
            <?php endforeach; ?>
                <?php endif;?>
            </tbody>
        </table>
    </div>
    <?php 
        $paginationInfo = $this->placeholder('pagination');
        if (!isset($paginationInfo->route)) {
            $paginationInfo->route  = 'admin/unit';
            $paginationInfo->params = array();
        }
    ?>
    <?php echo $this->paginationControl($this->unit, 'Sliding', 'layout/pagination'); ?>
</div>
