<legend>Lista de Referência</legend>
<table class="table table-condensed table-hover">
    <tr>
        <th class=""><?php echo $this->translate('TIPO'); ?></th>
        <th class=""><?php echo $this->translate('REFERÊNCIA'); ?></th>
        <th class=""><?php echo $this->translate('TELEFONE'); ?></th>
        <th class="col-md-1"><?php echo $this->translate('AÇÕES'); ?></th>
    </tr>
    <?php if (0 == count($this->customerSponsor)): ?>
        <tr class="alert alert-info">
            <td colspan="10" class="alert alert-info text-center"><?php echo $this->translate('Nenhum registro encontrado.') ?></td>
        </tr>
    <?php else: ?>
        <?php foreach ($this->customerSponsor as $customerSponsor) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($customerSponsor->getSponsorType()); ?></td>
                <td><?php echo $this->escapeHtml($customerSponsor->getSponsorName()); ?></td>
                <td><?php echo $this->phone($customerSponsor->getSponsorPhone()); ?></td>
                <td>
                    <div class="btn-group btn-group-xs pull-right">
                        <a class="btn btn-default" href="javascript: customerSponsorDelete('<?php echo $customerSponsor->getSponsorId();?>', '<?php echo $this->customerId;?>')"><i class="glyphicon glyphicon-remove"></i></a>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php endif; ?>
</table>