<h1 class="container-header"><i class="fa fa-dashboard"></i> Painel de Controle</h1>
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h1 class="panel-title">
                    <i class="fa fa-group"></i> 
                    Últimos Clientes
                    <i class="badge pull-right"><?php echo $this->customerCount; ?></i>
                </h1>
            </div>
        </div>
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h1 class="panel-title">
                    <i class="glyphicon glyphicon-stats"></i> 
                    Resumo de Propostas
                    <i class="badge pull-right" ><?php echo $this->proposalCount; ?></i>
                </h1>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h1 class="panel-title">
                    <i class="glyphicon glyphicon-share"></i> 
                    Meus Atalhos
                    <a href="#"><i class="glyphicon glyphicon-cog pull-right"></i></a>
                </h1>
            </div>
            <div class="panel-body">
                <div class="text-center">
                    
                </div>
            </div>
        </div>

        <div class="panel panel-warning">
            <div class="panel-heading">
                <h1 class="panel-title">
                    <i class="glyphicon glyphicon-stats"></i> 
                    Estatísticas
                    <a href="#"><i class="glyphicon glyphicon-cog pull-right"></i></a>
                </h1>
            </div>
            <div class="panel-body">
                
            </div>
        </div>
    </div>
</div>