<?php
$title = $this->headTitle($this->translate('Carregar Bancos'));
?>

<h1>
    <?php echo $title; ?> 
</h1>
<form action="" method="post">
    <label>Entre com o conteúdo do arquivo CSV</label>
    <textarea name="text" cols="500" rows="5" class="form-control"></textarea>
    <input type="submit" value="Carregar" class="btn btn-success" />
</form>
<div class="well">
    <?php echo $this->output; ?>
</div>
