<?php
$title = $this->headTitle($this->translate('Carregar Localizações'));
?>

<h1>
    <?php echo $title; ?> 
</h1>
<div class="row">
    <div class="col-md-5">
        <form action="" method="post">
            <div class="controls">
                <div class="controls-row">
                    <label>Entre com o conteúdo do arquivo CSV</label>
                    <textarea name="text" cols="500" rows="5" class="col-md-13"></textarea>
                </div>
                <div class="controls-row">
                    <input type="submit" value="Carregar" class="btn btn-success" />
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-7 well">
        <?php echo $this->output; ?>
    </div>
</div>
