<?php
$title = $this->translate('Conta do Cliente');
$this->headTitle($title);
$form = $this->form;
$form->prepare();
?>
<legend><h2><i class="glyphicon glyphicon-building"></i> <?php echo $this->escapeHtml($title); ?></h2></legend>

<div class="row">
    <div class="col-md-4">
        <?php echo $this->form()->openTag($form); ?>
        <?php $customerBankAccount = $form->get('customerBankAccount'); ?>
        <div class="form-group">
            <?php echo $this->formLabel($customerBankAccount->get('customerId')); ?>
            <?php echo $this->formSelect($customerBankAccount->get('customerId')); ?>

            <?php $bankAccount = $customerBankAccount->get('bankAccount'); ?>
            
            <?php echo $this->formLabel($bankAccount->get('bankAccountBank')); ?>
            <?php echo $this->formText($bankAccount->get('bankAccountBank')); ?>

            <?php echo $this->formLabel($bankAccount->get('bankAccountType')); ?>
            <?php echo $this->formSelect($bankAccount->get('bankAccountType')); ?>
            <div class="row">
                <div class="col-md-6">
                    <?php echo $this->formLabel($bankAccount->get('bankAccountAgency')); ?>
                    <?php echo $this->formText($bankAccount->get('bankAccountAgency')); ?>
                </div>
                <div class="col-md-6">
                    <?php echo $this->formLabel($bankAccount->get('bankAccountAccount')); ?>
                    <?php echo $this->formText($bankAccount->get('bankAccountAccount')); ?>
                </div>
            </div>

            <?php echo $this->formLabel($bankAccount->get('bankAccountSince')); ?>
            <?php echo $this->formText($bankAccount->get('bankAccountSince')); ?>
        </div>
        <?php echo $this->formHidden($form->get('security')); ?>
        <div class="btn-group">
            <?php echo $this->formElement($form->get('submit')); ?>
            <?php echo $this->formElement($form->get('cancel')); ?>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
    <div class="col-md-8">
        <div class="customer-bank-account-list"></div>
    </div>
</div>
<script type="text/javascript">
    customerBankAccountList('<?php echo $this->customerId ?>');
</script>