<!-- Image Slider -->
<section class="wrapper-sm bg-slider">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-lg-8 col-lg-offset-2">
                <div id="my-carousel" class="carousel slide">
                    <!-- Carousel items -->
                    <div class="carousel-inner">
                        <div class="item active"><img src="/img/app-1.png" alt="app"/></div>
                        <div class="item"><img src="/img/app-2.png" alt="app"/></div>
                    </div>
                    <!-- Carousel nav -->
                    <a class="carousel-control left" href="#my-carousel" data-slide="prev">&lsaquo;</a>
                    <a class="carousel-control right" href="#my-carousel" data-slide="next">&rsaquo;</a>
                </div><!-- /.carousel -->
                <h1 class="carousel-title">Sua empresa na internet</h1>
                <p class="carousel-subtitle">O próximo grande negócio será fechado aqui e você fará parte dele.</p>
            </div>
        </div>
    </div>
</section>

<section class="wrapper-lg" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h1>Who we are?</h1>
                <p>We design and develop beautiful apps for iOS, working with your idea and develop your proposal all the way through to the end product, keeping track of everything you need to bring your project to fruition.</p>
                <p>We can give you support defining the usability and navigation of your app at the beginning of the project. Development and design work together to create a unique product with the best user experience and get users to enjoy every second with the app.</p>
            </div>
        </div>
        <br class="spacer-md">
        <hr>
        <br class="spacer-md">
        <div class="row">
            <div class="col-md-6 col-lg-4 col-lg-offset-2">
                <h1>What we do?</h1>
                <p>Creating wireframes on your favorite notebook. Take your time and sketch your interface carefully. Pen &amp; paper are the best tools. Complicated software only gets in the way.</p>
                <h3>Want to be creative?</h3>
                <p>Create a storyboard by linking your sketches together with "link spots". Press play and simulate your user interface to make sure everything flows correctly.</p>
            </div>
            <div class="col-md-6 col-lg-4">
                <h3>Our Skills</h3>
                <p>iOS Development</p>
                <div class="progress progress-striped">
                    <div class="progress-bar progress-bar-info" style="width: 100%"></div>
                </div>
                <p>UI / UX</p>
                <div class="progress progress-striped">
                    <div class="progress-bar progress-bar-success" style="width: 100%"></div>
                </div>
                <p>App design</p>
                <div class="progress progress-striped">
                    <div class="progress-bar progress-bar-warning" style="width: 100%"></div>
                </div>
            </div>
        </div>
        <br class="spacer-md">
        <hr>
        <br class="spacer-md">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <div class="well">
                    <h4>Copyright and Content Ownership</h4>
                    <p>We claim no intellectual property rights over the material you provide to the Service. Your profile and materials uploaded remain yours. However, by setting your pages to be viewed publicly, you agree to allow others to view your Content. By setting your repositories to be viewed publicly, you agree to allow others to view and comment your mockups.</p>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="wrapper-sm" id="pricing">
    <div class="wrapper-lg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h1>Shut up and take my money</h1>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="plan">
                    <div class="plan-name">
                        <h3>Starter Pack</h3>
                    </div>
                    <div class="plan-info">
                        <p>Get a helping hand with our products in the members only premium area</p>
                    </div>
                    <div class="plan-price">
                        <h1>$12 <small>/month</small></h1>
                    </div>
                    <ul class="plan-features">
                        <li><i class="icon-ok"></i> Unlimited Support <i class="icon-info-sign" data-toggle="tooltip" title="Restrictions apply"></i></li>
                        <li><i class="icon-ok"></i> Basic Options</li>
                        <li><i class="icon-remove"></i> 100GB Storage</li>
                        <li><i class="icon-remove"></i> Ad Free Streaming</li>
                    </ul>
                    <div class="plan-cta">
                        <p>Unlimited ad-free streaming, unlimited viewers</p>
                        <br class="spacer-md">
                        <a href="#" class="btn btn-default btn-lg">Get it now! &raquo;</a>
                    </div>
                </div><!-- /.plan -->
            </div>
            <div class="col-md-4">
                <div class="plan plan-featured">
                    <div class="plan-name">
                        <h3>Starter Pack</h3>
                    </div>
                    <div class="plan-info">
                        <p>Get a helping hand with our products in the members only premium area</p>
                    </div>
                    <div class="plan-price">
                        <h1>$24 <small>/month</small></h1>
                    </div>
                    <ul class="plan-features">
                        <li><i class="icon-ok"></i> Unlimited Support <i class="icon-info-sign" data-toggle="tooltip" title="Restrictions apply"></i></li>
                        <li><i class="icon-ok"></i> Basic Options</li>
                        <li><i class="icon-remove"></i> 100GB Storage</li>
                        <li><i class="icon-remove"></i> Ad Free Streaming</li>
                    </ul>
                    <div class="plan-cta">
                        <p>Unlimited ad-free streaming, unlimited viewers</p>
                        <br class="spacer-md">
                        <a href="#" class="btn btn-primary btn-lg">Get it now! &raquo;</a>
                    </div>
                </div><!-- /.plan -->
            </div>
            <div class="col-md-4">
                <div class="plan">
                    <div class="plan-name">
                        <h3>Starter Pack</h3>
                    </div>
                    <div class="plan-info">
                        <p>Get a helping hand with our products in the members only premium area</p>
                    </div>
                    <div class="plan-price">
                        <h1>$48 <small>/month</small></h1>
                    </div>
                    <ul class="plan-features">
                        <li><i class="icon-ok"></i> Unlimited Support <i class="icon-info-sign" data-toggle="tooltip" title="Restrictions apply"></i></li>
                        <li><i class="icon-ok"></i> Basic Options</li>
                        <li><i class="icon-remove"></i> 100GB Storage</li>
                        <li><i class="icon-remove"></i> Ad Free Streaming</li>
                    </ul>
                    <div class="plan-cta">
                        <p>Unlimited ad-free streaming, unlimited viewers</p>
                        <br class="spacer-md">
                        <a href="#" class="btn btn-default btn-lg">Get it now! &raquo;</a>
                    </div>
                </div><!-- /.plan -->
            </div>
        </div>
    </div>
</section>