<?php
$title = $this->translate('Editar Situação do Funcionário');
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('admin/employee-status/edit', array('id' => $this->id)));
$form->prepare();
?>
<h1 class="container-header"><i class="fa fa-compass"></i> <?php echo $this->escapeHtml($title); ?></h1>
<?php echo $this->form()->openTag($form); ?>
<div class="form-group">
    <?php $employeeStatus = $form->get('employeeStatus'); ?>
    <?php echo $this->formRow($employeeStatus->get('employeeStatusId')); ?>
    <div class="row">
        <div class="col-md-4">
            <?php echo $this->formLabel($employeeStatus->get('employeeStatusName')); ?>
            <?php echo $this->formText($employeeStatus->get('employeeStatusName')); ?>
        </div>
    </div>
</div>
<?php echo $this->formHidden($form->get('security')); ?>
<div class="btn-group">
    <?php echo $this->formElement($form->get('submit')); ?>
    <?php echo $this->formElement($form->get('cancel')); ?>
</div>
<?php echo $this->form()->closeTag(); ?>
