<?php
$title = $this->translate('Situação do Funcionário');
$this->headTitle($title);
?>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-6">
                <h4 class="panel-title"><i class="fa fa-compass"></i> <?php echo $this->escapeHtml($title); ?></h4>
            </div>
            <div class="col-md-6">
                <div class="btn-group btn-group-sm pull-right">
                    <a class="btn btn-default" href="<?php echo $this->url('admin/employee-status/add', array('action' => 'add')); ?>"> <i class="glyphicon glyphicon-plus"></i> <?php echo $this->translate('Novo'); ?></a>
                </div>
            </div>
        </div>
    </div>
    <table class="table table-condensed table-hover">
        <tr>
            <th colspan="10"><?php echo $this->translate('SITUAÇÃO DO FUNCIONÁRIO'); ?></th>
        </tr>
        <?php if (0 == count($this->employeeStatus)): ?>
            <tr>
                <td colspan="10" class="alert alert-info text-center"><?php echo $this->translate('Não há registros no banco de dados.') ?></td>
            </tr>
        <?php else: ?>
            <?php foreach ($this->employeeStatus as $employeeStatus) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($employeeStatus->getEmployeeStatusName()); ?></td>
                    <td>
                        <div class="btn-group btn-group-xs pull-right">
                            <a class="btn btn-default" href="<?php echo $this->url('admin/employee-status/edit', array('action' => 'edit', 'id' => $employeeStatus->getEmployeeStatusId()))
                ?>"><i class="glyphicon glyphicon-edit"></i></a>
                            <a class="btn btn-default" href="<?php echo $this->url('admin/employee-status/delete', array('action' => 'delete', 'id' => $employeeStatus->getEmployeeStatusId()))
                ?>"><i class="glyphicon glyphicon-remove"></i></a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
        </tbody>
    </table>
    <div class="panel-footer">
        <?php
        $paginationInfo = $this->placeholder('pagination');
        if (!isset($paginationInfo->route)) {
            $paginationInfo->route = 'admin/employee-status';
            $paginationInfo->params = array();
        }
        ?>
        <?php echo $this->paginationControl($this->employeeStatus, 'Sliding', 'layout/pagination'); ?>
    </div>
</div>
