<?php
$title = $this->translate('Compras');
$this->headTitle($title);
?>
<h1 class="row-fluid">
    <div class="span6">
        <?php echo $this->escapeHtml($title); ?>
    </div>
    <div class="pull-right">
        <div class="btn-group">
            <a class="btn" href="<?php echo $this->url('admin/purchase/add', array('action' => 'add')); ?>"> <i class="icon-plus"></i> <?php echo $this->translate('Novo'); ?></a>
        </div>
    </div> 
</h1>
<div class="row-fluid">
    <div class="span2">
        <div class="widget">
            <div class="widget-header">
                <h3>Total de Compras</h3>
            </div>
            <div class="widget-content" dir="rtl">
                <h4 class="text-warning"><small>Hoje</small> <?php echo $this->currency($this->totalOfDay['totalOfDay']); ?></h4>
                <h4 class="text-warning"><small>Mês Atual</small> <?php echo $this->currency($this->monthTotal['monthTotal']); ?></h4>
                <h4 class="text-warning"><small>Total</small> <?php echo $this->currency($this->total['total']); ?></h4>
            </div>
        </div>
    </div>

    <div class="span10">
        <div class="widget widget-table">
            <div class="widget-header">
                <i class="manager-icon-nameplate"></i>
                <h3>Compras</h3>
            </div>
            <div class="widget-content">
                <table class="table table-bpurchaseed">
                    <tr>
                        <th class="span1"><?php echo $this->translate('#'); ?></th>
                        <th class="span1"><?php echo $this->translate('Código'); ?></th>
                        <th class="span1"><?php echo $this->translate('Data'); ?></th>
                        <th class=""><?php echo $this->translate('Fornecedor'); ?></th>
                        <th class="span2"><?php echo $this->translate('Valor'); ?></th>
                        <th class="span1"><?php echo $this->translate('Ações'); ?></th>
                    </tr>
                    <?php if (0 == count($this->purchase)): ?>
                        <tr>
                            <td colspan="10"><?php echo $this->info($this->translate('Não há registros no banco de dados.')); ?></td>
                        </tr>
                    <?php else: ?>
                        <?php foreach ($this->purchase as $purchase) : ?>
                            <tr>
                                <td><?php echo $this->escapeHtml($purchase->getPurchaseId()); ?></td>
                                <td><?php echo $this->escapeHtml($purchase->getPurchaseUid()); ?></td>
                                <td><?php echo $this->escapeHtml($purchase->getPurchaseDate()); ?></td>
                                <td><?php echo $this->escapeHtml($purchase->getSupplierId()->getSupplierName()); ?></td>
                                <td><?php echo $this->currency($purchase->getPurchaseTotal()); ?></td>
                                <td>
                                    <div class="btn-group">
                                        <a class="btn btn-mini btn-info" href="<?php echo $this->url('admin/purchase/view', array('action' => 'view', 'id' => $purchase->getPurchaseId()))
                            ?>"><i class="icon-search"></i></a>
                                        <a class="btn btn-mini btn-danger" href="<?php echo $this->url('admin/purchase/delete', array('action' => 'delete', 'id' => $purchase->getPurchaseId()))
                            ?>"><i class="icon-remove"></i></a>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    </tbody>
                </table>
            </div>
            <?php
            $paginationInfo = $this->placeholder('pagination');
            if (!isset($paginationInfo->route)) {
                $paginationInfo->route = 'admin/purchase';
                $paginationInfo->params = array();
            }
            ?>
            <?php echo $this->paginationControl($this->purchase, 'Sliding', 'layout/pagination'); ?>
        </div>
    </div>
</div>